// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************


/// <summary>
/// Add this unit to the uses of a project that renders TMVCActiveRecord entities with TemplatePro:
/// its initialization registers TTProConfiguration.OnGetFieldMetadata, so {{for f in entity.@@fields}}
/// and the forms library (auto) follow the ActiveRecord mapping. It is a separate unit because
/// MVCFramework.ActiveRecord pulls FireDAC, which the TemplatePro renderer must not force on everyone.
/// </summary>
unit MVCFramework.View.Renderers.TemplatePro.ActiveRecord;

interface

implementation

uses
  System.SysUtils,
  System.Rtti,
  MVCFramework,
  MVCFramework.ActiveRecord,
  MVCFramework.Validators,
  TemplatePro;

type
  TMVCActiveRecordAccess = class(TMVCActiveRecord); // reaches the protected fTableMap

procedure ApplyAttributes(const aAttributes: TArray<TCustomAttribute>; const aMetadata: TTProFieldMetadata);
var
  lAttr: TCustomAttribute;
begin
  for lAttr in aAttributes do
  begin
    if lAttr is MVCRequired then
      aMetadata.Required := True
    else if lAttr is MVCMaxLength then
      aMetadata.Size := MVCMaxLength(lAttr).MaxLength
    else if lAttr is MVCMaxLengthAttribute then // what [MVCMaxLength(n)] resolves to when MVCFramework is in uses
      aMetadata.Size := MVCMaxLengthAttribute(lAttr).Value;
  end;
end;

procedure ActiveRecordFieldMetadata(const aObject: TObject; const aPropertyName: string;
  const aMetadata: TTProFieldMetadata);
// ponytail: no per-class cache - RTTI objects and attributes are already cached by the RTTI pool and
// the table map (built once per class by ActiveRecord); only read-only access here, so it is thread-safe.
var
  lTableMap: TMVCTableMap;
  lField, lRTTIField: TRttiField;
  lProp: TRttiProperty;
  lFieldInfo: TFieldInfo;
  lOptions: TMVCActiveRecordFieldOptions;
  lAttr: TCustomAttribute;
begin
  if not (aObject is TMVCActiveRecord) then
    Exit;
  lTableMap := TMVCActiveRecordAccess(aObject).fTableMap;
  if lTableMap = nil then
    Exit;

  // property P is mapped by the private field fP (same convention as TMVCActiveRecord.GetMapping)
  lField := nil;
  for lRTTIField in lTableMap.fProps do
    if SameText(lRTTIField.Name, 'f' + aPropertyName) then
    begin
      lField := lRTTIField;
      Break;
    end;

  if (lField <> nil) and lTableMap.TryGetPKOptions(lField, lOptions) then
    aMetadata.Hidden := True // primary keys are not in fMap
  else if (lField <> nil) and lTableMap.fMap.TryGetValue(lField, lFieldInfo) then
    lOptions := lFieldInfo.FieldOptions
  else
  begin
    aMetadata.Visible := False; // not persisted
    lOptions := [];
  end;
  if foAutoGenerated in lOptions then
    aMetadata.Hidden := True;
  if foReadOnly in lOptions then
    aMetadata.ReadOnly := True;

  if lField <> nil then
    ApplyAttributes(lField.GetAttributes, aMetadata);
  lProp := lTableMap.fRTTIType.GetProperty(aPropertyName);
  if lProp <> nil then
  begin
    ApplyAttributes(lProp.GetAttributes, aMetadata);
    for lAttr in lProp.GetAttributes do
      if lAttr is MVCDocAttribute then
        aMetadata.DisplayLabel := MVCDocAttribute(lAttr).Value;
  end;
end;

initialization

TTProConfiguration.OnGetFieldMetadata := ActiveRecordFieldMetadata;

end.
