// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// ***************************************************************************

unit MVCFramework.SQLGenerators.MariaDB;

{$I dmvcframework.inc}

interface

uses
  System.SysUtils,
  MVCFramework.ActiveRecord,
  MVCFramework.SQLGenerators.MySQL;

type
  /// <summary>
  /// MariaDB SQL generator. Inherits from MySQL and overrides INSERT to use
  /// `INSERT ... RETURNING ...` (MariaDB 10.5+). UPDATE and DELETE are inherited
  /// from MySQL because MariaDB lacks UPDATE RETURNING (only INSERT, REPLACE,
  /// and DELETE support RETURNING in MariaDB).
  ///
  /// Drop-in compatibility: code written for MySQL also works on MariaDB
  /// (MariaDB executes all MySQL SQL). The reverse is NOT guaranteed -
  /// MariaDB-specific syntax fails on MySQL. Register your connection with
  /// backend tag 'mariadb' to opt into the MariaDB optimizations.
  /// </summary>
  TMVCSQLGeneratorMariaDB = class(TMVCSQLGeneratorMySQL)
  public
    function HandlesRefreshNatively: Boolean; override;
    function CreateInsertSQL(const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord): string; override;
  end;

implementation

function TMVCSQLGeneratorMariaDB.HandlesRefreshNatively: Boolean;
begin
  // INSERT supports RETURNING natively in MariaDB 10.5+.
  // UPDATE does NOT - UPDATE RETURNING is unsupported in MariaDB as of
  // 11.x. So UPDATE goes through the parent's fallback SELECT.
  // We report False here to keep the generic Update path working; for
  // INSERT, the override below emits RETURNING in-statement so the
  // post-Insert RefreshFromDB call has nothing to do (the RETURNING
  // result has already populated the instance via FireDAC).
  // Net behavior: INSERT is one-statement, UPDATE uses fallback SELECT.
  Result := False;
end;

function TMVCSQLGeneratorMariaDB.CreateInsertSQL(const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lReturningCols: string;
  lLegacyPos: Integer;
begin
  // Start from the MySQL parent's INSERT (which emits the legacy
  // `;SELECT LAST_INSERT_ID() as pk` trailing statement when foAutoGenerated).
  // NOTE: parent appends `;SELECT LAST_INSERT_ID() as ` (no space after
  // semicolon). If the parent's exact format changes in the future, this
  // strip needs updating - keep this comment to flag the coupling.
  Result := inherited CreateInsertSQL(TableMap, ARInstance);

  // If the parent appended the `;SELECT LAST_INSERT_ID()` trailing, strip it.
  lLegacyPos := Pos(';SELECT LAST_INSERT_ID()', Result);
  if lLegacyPos > 0 then
    Result := TrimRight(Copy(Result, 1, lLegacyPos - 1));

  // Append RETURNING with PK + RefreshFields. MariaDB 10.5+ supports this
  // for INSERT. The auto-generated PK comes back through the result-set,
  // not via LAST_INSERT_ID().
  lReturningCols := BuildReturningColumnList(TableMap);
  if lReturningCols <> '' then
    Result := Result + ' RETURNING ' + lReturningCols;
end;

initialization

TMVCSQLGeneratorRegistry.Instance.RegisterSQLGenerator(
  'mariadb', TMVCSQLGeneratorMariaDB);

finalization

TMVCSQLGeneratorRegistry.Instance.UnRegisterSQLGenerator('mariadb');

end.
