// *************************************************************************** }
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

unit MVCFramework.SQLGenerators.PostgreSQL;

interface

uses
  System.Rtti,
  System.Generics.Collections,
  MVCFramework.ActiveRecord,
  MVCFramework.Commons,
  MVCFramework.RQL.Parser;

type
  TMVCSQLGeneratorPostgreSQL = class(TMVCSQLGenerator)
  protected
    function GetCompilerClass: TRQLCompilerClass; override;
  public
    function HasNativeUUID: Boolean; override;
    function CreateInsertSQL(
      const TableMap: TMVCTableMap; const ARInstance: TMVCActiveRecord): string; override;
    function CreateUpdateSQL(
      const TableMap: TMVCTableMap; const ARInstance: TMVCActiveRecord): string; overload; override;
    function CreateUpdateSQL(const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord;
      const ADirtyFields: TArray<string>): string; overload; override;
    function GetSequenceValueSQL(const PKFieldName: string;
      const SequenceName: string;
      const Step: Integer = 1): string; override;
  end;

implementation

{
  All identifiers (including column names) that are not double-quoted are folded to
  lower case in PostgreSQL. Column names that were created with double-quotes and thereby
  retained upper-case letters (and/or other syntax violations) have to be double-quoted
  for the rest of their life.
}

uses
  System.SysUtils,
  MVCFramework.RQL.AST2PostgreSQL;

function TMVCSQLGeneratorPostgreSQL.CreateInsertSQL(const TableMap: TMVCTableMap; const ARInstance: TMVCActiveRecord): string;
var
  lKeyValue: TPair<TRttiField, TFieldInfo>;
  lSB: TStringBuilder;
  lPKInInsert: Boolean;
  lFieldName: String;
  lReturningCols: string;
begin
  lPKInInsert := (not TableMap.fPrimaryKeyFieldName.IsEmpty) and (not(TMVCActiveRecordFieldOption.foAutoGenerated in TableMap.fPrimaryKeyOptions));
  lPKInInsert := lPKInInsert and (not(TMVCActiveRecordFieldOption.foReadOnly in TableMap.fPrimaryKeyOptions));
  lSB := TStringBuilder.Create;
  try
    lSB.Append('INSERT INTO ' + GetTableNameForSQL(TableMap.fTableName) + ' (');
    if lPKInInsert then
    begin
      lSB.Append(GetFieldNameForSQL(TableMap.fPrimaryKeyFieldName) + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(GetFieldNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.Insertable then
      begin
        lSB.Append(GetFieldNameForSQL(lKeyValue.Value.FieldName) + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(') values (');
    if lPKInInsert then
    begin
      lSB.Append(':' + GetParamNameForSQL(TableMap.fPrimaryKeyFieldName) + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(':' + GetParamNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.IsVersion then
      begin
        lSB.Append(OBJECT_VERSION_STARTING_VALUE + ',');
      end else if lKeyValue.Value.Insertable then
      begin
        lSB.Append(':' + GetParamNameForSQL(lKeyValue.Value.FieldName) + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(')');

    lReturningCols := BuildReturningColumnList(TableMap);
    if lReturningCols <> '' then
      lSB.Append(' RETURNING ' + lReturningCols);
    Result := lSB.ToString;
  finally
    lSB.Free;
  end;
end;

function TMVCSQLGeneratorPostgreSQL.CreateUpdateSQL(const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lFieldInfo: TFieldInfo;
  lReturningCols: string;
  lFirst: Boolean;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance);
  // For UPDATE we only need foRefresh columns back (PK is already known)
  lReturningCols := '';
  lFirst := True;
  for lFieldInfo in TableMap.RefreshFields do
  begin
    if lFirst then
    begin
      lReturningCols := GetFieldNameForSQL(lFieldInfo.FieldName);
      lFirst := False;
    end
    else
      lReturningCols := lReturningCols + ', ' + GetFieldNameForSQL(lFieldInfo.FieldName);
  end;
  if lReturningCols <> '' then
    Result := Result + ' RETURNING ' + lReturningCols;
end;

function TMVCSQLGeneratorPostgreSQL.CreateUpdateSQL(const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord;
  const ADirtyFields: TArray<string>): string;
var
  lFieldInfo: TFieldInfo;
  lReturningCols: string;
  lFirst: Boolean;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance, ADirtyFields);
  // For UPDATE we only need foRefresh columns back (PK is already known)
  lReturningCols := '';
  lFirst := True;
  for lFieldInfo in TableMap.RefreshFields do
  begin
    if lFirst then
    begin
      lReturningCols := GetFieldNameForSQL(lFieldInfo.FieldName);
      lFirst := False;
    end
    else
      lReturningCols := lReturningCols + ', ' + GetFieldNameForSQL(lFieldInfo.FieldName);
  end;
  if lReturningCols <> '' then
    Result := Result + ' RETURNING ' + lReturningCols;
end;

function TMVCSQLGeneratorPostgreSQL.GetCompilerClass: TRQLCompilerClass;
begin
  Result := TRQLPostgreSQLCompiler;
end;

function TMVCSQLGeneratorPostgreSQL.GetSequenceValueSQL(const PKFieldName,
  SequenceName: string; const Step: Integer): string;
begin
  Result := Format('SELECT nextval(''%s'') %s', [SequenceName, GetFieldNameForSQL(PKFieldName)]);
end;

function TMVCSQLGeneratorPostgreSQL.HasNativeUUID: Boolean;
begin
  Result := True;
end;

initialization

TMVCSQLGeneratorRegistry.Instance.RegisterSQLGenerator('postgresql', TMVCSQLGeneratorPostgreSQL);

finalization

TMVCSQLGeneratorRegistry.Instance.UnRegisterSQLGenerator('postgresql');

end.
