// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

// Durable IMVCRefreshTokenStore backed by TMVCActiveRecord. Kept in a companion
// unit so MVCFramework.JWT.RefreshToken does not force a FireDAC dependency.

unit MVCFramework.JWT.RefreshToken.ActiveRecord;

{$I dmvcframework.inc}

interface

uses
  System.SysUtils,
  System.DateUtils,
  System.Generics.Collections,
  MVCFramework.ActiveRecord,
  MVCFramework.JWT.RefreshToken;

type
  [MVCTable('refresh_tokens')]
  TMVCRefreshTokenRecord = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    fID: Int64;
    [MVCTableField('token_hash')]
    fTokenHash: string;
    [MVCTableField('family_id')]
    fFamilyID: string;
    [MVCTableField('username')]
    fUsername: string;
    [MVCTableField('roles')]
    fRoles: string;
    [MVCTableField('expires_at')]
    fExpiresAt: TDateTime;
    [MVCTableField('used')]
    fUsed: Boolean;
  public
    property ID: Int64 read fID write fID;
    property TokenHash: string read fTokenHash write fTokenHash;
    property FamilyID: string read fFamilyID write fFamilyID;
    property Username: string read fUsername write fUsername;
    property Roles: string read fRoles write fRoles;
    property ExpiresAt: TDateTime read fExpiresAt write fExpiresAt;
    property Used: Boolean read fUsed write fUsed;
  end;

  // Durable store. The named FireDAC ConnectionDef must already be registered
  // (FDManager.AddConnectionDef) before the store is used. A connection is
  // acquired from the pool per call, so it works even in OnBeforeRouting,
  // before the ActiveRecord middleware/filter runs.
  TMVCActiveRecordRefreshTokenStore = class(TInterfacedObject, IMVCRefreshTokenStore)
  private
    fConnectionDefName: string;
    procedure RevokeFamilyNoConn(const AFamilyID: string);
  public
    constructor Create(const AConnectionDefName: string);
    function Issue(const AUsername, ARoles: string; const ATTLSeconds: Integer): string;
    function Rotate(const AOldRefreshToken: string; const ATTLSeconds: Integer): TMVCRefreshTokenRotation;
    procedure Revoke(const ARefreshToken: string);
  end;

implementation

constructor TMVCActiveRecordRefreshTokenStore.Create(const AConnectionDefName: string);
begin
  inherited Create;
  fConnectionDefName := AConnectionDefName;
end;

procedure TMVCActiveRecordRefreshTokenStore.RevokeFamilyNoConn(const AFamilyID: string);
var
  lList: TObjectList<TMVCRefreshTokenRecord>;
  lRec: TMVCRefreshTokenRecord;
begin
  lList := TMVCActiveRecord.Where<TMVCRefreshTokenRecord>('family_id = ?', [AFamilyID]);
  try
    for lRec in lList do
      lRec.Delete;
  finally
    lList.Free;
  end;
end;

function TMVCActiveRecordRefreshTokenStore.Issue(const AUsername, ARoles: string;
  const ATTLSeconds: Integer): string;
var
  lToken: string;
  lRec: TMVCRefreshTokenRecord;
  lGuid: TGUID;
begin
  lToken := MVCNewOpaqueRefreshToken;
  CreateGUID(lGuid);
  ActiveRecordConnectionsRegistry.AddDefaultConnection(fConnectionDefName);
  try
    lRec := TMVCRefreshTokenRecord.Create;
    try
      lRec.TokenHash := MVCRefreshTokenHash(lToken);
      lRec.FamilyID := GUIDToString(lGuid);
      lRec.Username := AUsername;
      lRec.Roles := ARoles;
      lRec.ExpiresAt := Now + (ATTLSeconds * OneSecond);
      lRec.Used := False;
      lRec.Insert;
    finally
      lRec.Free;
    end;
  finally
    ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  end;
  Result := lToken;
end;

function TMVCActiveRecordRefreshTokenStore.Rotate(const AOldRefreshToken: string;
  const ATTLSeconds: Integer): TMVCRefreshTokenRotation;
var
  lHash, lNewToken: string;
  lOld, lNew: TMVCRefreshTokenRecord;
begin
  Result.Status := rtsNotFound;
  Result.NewRefreshToken := '';
  lHash := MVCRefreshTokenHash(AOldRefreshToken);
  ActiveRecordConnectionsRegistry.AddDefaultConnection(fConnectionDefName);
  try
    TMVCActiveRecord.CurrentConnection.StartTransaction;
    try
      lOld := TMVCActiveRecord.GetFirstByWhere<TMVCRefreshTokenRecord>(
        'token_hash = ?', [lHash], False);
      if lOld = nil then
      begin
        TMVCActiveRecord.CurrentConnection.Commit;
        Exit; // rtsNotFound
      end;
      try
        if lOld.Used then
        begin
          RevokeFamilyNoConn(lOld.FamilyID); // stolen token replayed
          Result.Status := rtsReuseDetected;
        end
        else if lOld.ExpiresAt < Now then
        begin
          lOld.Delete;
          Result.Status := rtsExpired;
        end
        else
        begin
          lOld.Used := True;
          lOld.Update;
          lNewToken := MVCNewOpaqueRefreshToken;
          lNew := TMVCRefreshTokenRecord.Create;
          try
            lNew.TokenHash := MVCRefreshTokenHash(lNewToken);
            lNew.FamilyID := lOld.FamilyID;
            lNew.Username := lOld.Username;
            lNew.Roles := lOld.Roles;
            lNew.ExpiresAt := Now + (ATTLSeconds * OneSecond);
            lNew.Used := False;
            lNew.Insert;
          finally
            lNew.Free;
          end;
          Result.Status := rtsOK;
          Result.Username := lOld.Username;
          Result.Roles := lOld.Roles;
          Result.NewRefreshToken := lNewToken;
        end;
      finally
        lOld.Free;
      end;
      TMVCActiveRecord.CurrentConnection.Commit;
    except
      TMVCActiveRecord.CurrentConnection.Rollback;
      raise;
    end;
  finally
    ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  end;
end;

procedure TMVCActiveRecordRefreshTokenStore.Revoke(const ARefreshToken: string);
var
  lRec: TMVCRefreshTokenRecord;
begin
  ActiveRecordConnectionsRegistry.AddDefaultConnection(fConnectionDefName);
  try
    lRec := TMVCActiveRecord.GetFirstByWhere<TMVCRefreshTokenRecord>(
      'token_hash = ?', [MVCRefreshTokenHash(ARefreshToken)], False);
    if lRec <> nil then
      try
        RevokeFamilyNoConn(lRec.FamilyID);
      finally
        lRec.Free;
      end;
  finally
    ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  end;
end;

end.
