// *************************************************************************** }
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

unit MVCFramework.SQLGenerators.Sqlite;

interface

uses
  System.Rtti,
  System.Generics.Collections,
  MVCFramework.ActiveRecord,
  MVCFramework.Commons,
  MVCFramework.RQL.Parser;

type
  TMVCSQLGeneratorSQLite = class(TMVCSQLGenerator)
  protected
    function GetCompilerClass: TRQLCompilerClass; override;
  public
    function CreateInsertSQL(
      const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord): string; override;
    function CreateUpdateSQL(
      const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord): string; overload; override;
    function CreateUpdateSQL(const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord;
      const ADirtyFields: TArray<string>): string; overload; override;
    function HasSequences: Boolean; override;
  end;

implementation

uses
  System.SysUtils,
  MVCFramework.RQL.AST2SQLite;

function TMVCSQLGeneratorSQLite.CreateInsertSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lKeyValue: TPair<TRttiField, TFieldInfo>;
  lSB: TStringBuilder;
  lPKInInsert: Boolean;
  lFieldName: String;
  lReturningCols: string;
begin
  lPKInInsert := (not TableMap.fPrimaryKeyFieldName.IsEmpty) and
    (not(TMVCActiveRecordFieldOption.foAutoGenerated in TableMap.fPrimaryKeyOptions));
  lPKInInsert := lPKInInsert and (not(TMVCActiveRecordFieldOption.foReadOnly in TableMap.fPrimaryKeyOptions));
  lSB := TStringBuilder.Create;
  try
    lSB.Append('INSERT INTO ' + GetTableNameForSQL(TableMap.fTableName) + ' (');
    if lPKInInsert then
    begin
      lSB.Append(GetFieldNameForSQL(TableMap.fPrimaryKeyFieldName) + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(GetFieldNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.Insertable then
      begin
        lSB.Append(GetFieldNameForSQL(lKeyValue.Value.FieldName) + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(') values (');
    if lPKInInsert then
    begin
      lSB.Append(':' + GetParamNameForSQL(TableMap.fPrimaryKeyFieldName) + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(':' + GetParamNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.IsVersion then
      begin
        lSB.Append(OBJECT_VERSION_STARTING_VALUE + ',');
      end else if lKeyValue.Value.Insertable then
      begin
        lSB.Append(':' + GetParamNameForSQL(lKeyValue.Value.FieldName) + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(')');

    // Use native RETURNING only when foRefresh fields are present.
    // For the plain foAutoGenerated-PK-only case, the legacy last_insert_rowid()
    // approach is used instead because FireDAC executes SQLite statements with
    // BusyTimeout=0 per statement, and a RETURNING clause holds the write lock
    // while the result row is being read -- causing SQLITE_BUSY failures under
    // parallel load.  last_insert_rowid() is committed before the trailing
    // SELECT runs, so parallel writers are never blocked.
    if TableMap.RefreshFields.Count > 0 then
    begin
      lReturningCols := BuildReturningColumnList(TableMap);
      if lReturningCols <> '' then
        lSB.Append(' RETURNING ' + lReturningCols);
    end
    else if TMVCActiveRecordFieldOption.foAutoGenerated in TableMap.fPrimaryKeyOptions then
    begin
      lSB.Append(' ; SELECT last_insert_rowid() as ' +
        GetFieldNameForSQL(TableMap.fPrimaryKeyFieldName) + ';');
    end;
    Result := lSB.ToString;
  finally
    lSB.Free;
  end;
end;

function TMVCSQLGeneratorSQLite.CreateUpdateSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lFieldInfo: TFieldInfo;
  lReturningCols: string;
  lFirst: Boolean;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance);
  if TableMap.RefreshFields.Count = 0 then
    Exit;
  lReturningCols := '';
  lFirst := True;
  for lFieldInfo in TableMap.RefreshFields do
  begin
    if lFirst then
    begin
      lReturningCols := GetFieldNameForSQL(lFieldInfo.FieldName);
      lFirst := False;
    end
    else
      lReturningCols := lReturningCols + ', ' + GetFieldNameForSQL(lFieldInfo.FieldName);
  end;
  if lReturningCols <> '' then
    Result := Result + ' RETURNING ' + lReturningCols;
end;

function TMVCSQLGeneratorSQLite.CreateUpdateSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord;
  const ADirtyFields: TArray<string>): string;
var
  lFieldInfo: TFieldInfo;
  lReturningCols: string;
  lFirst: Boolean;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance, ADirtyFields);
  if TableMap.RefreshFields.Count = 0 then
    Exit;
  lReturningCols := '';
  lFirst := True;
  for lFieldInfo in TableMap.RefreshFields do
  begin
    if lFirst then
    begin
      lReturningCols := GetFieldNameForSQL(lFieldInfo.FieldName);
      lFirst := False;
    end
    else
      lReturningCols := lReturningCols + ', ' + GetFieldNameForSQL(lFieldInfo.FieldName);
  end;
  if lReturningCols <> '' then
    Result := Result + ' RETURNING ' + lReturningCols;
end;

function TMVCSQLGeneratorSQLite.GetCompilerClass: TRQLCompilerClass;
begin
  Result := TRQLSQLiteCompiler;
end;

function TMVCSQLGeneratorSQLite.HasSequences: Boolean;
begin
  Result := False;
end;

initialization

TMVCSQLGeneratorRegistry.Instance.RegisterSQLGenerator('sqlite', TMVCSQLGeneratorSQLite);

finalization

TMVCSQLGeneratorRegistry.Instance.UnRegisterSQLGenerator('sqlite');

end.
