// *************************************************************************** }
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

unit MVCFramework.SQLGenerators.MSSQL;

interface

uses
  {
    //do not include these 2 unit in this unit
    //because it will not compiles in Delphi Pro
  FireDAC.Phys.MSSQLDef,
  FireDAC.Phys.MSSQL,
  }
  System.Generics.Collections,
  MVCFramework.RQL.Parser,
  MVCFramework.ActiveRecord,
  MVCFramework.Commons;

type
  TMVCSQLGeneratorMSSQL = class(TMVCSQLGenerator)
  protected
    function GetCompilerClass: TRQLCompilerClass; override;
    function BuildOutputClause(const TableMap: TMVCTableMap;
      const ARefreshFieldsOnly: Boolean): string;
    function BuildSoftDeleteWhereSuffix(const TableMap: TMVCTableMap): string; override;
    function BuildSoftDeleteSetDeleted(const TableMap: TMVCTableMap): string; override;
    function BuildSoftDeleteSetRestored(const TableMap: TMVCTableMap): string; override;
  public
    function CreateInsertSQL(
      const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord): string; override;
    function CreateUpdateSQL(
      const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord): string; overload; override;
    function CreateUpdateSQL(const TableMap: TMVCTableMap;
      const ARInstance: TMVCActiveRecord;
      const ADirtyFields: TArray<string>): string; overload; override;
  end;

implementation

uses
  System.Rtti,
  System.SysUtils,
  MVCFramework.RQL.AST2MSSQL;

function TMVCSQLGeneratorMSSQL.BuildOutputClause(const TableMap: TMVCTableMap;
  const ARefreshFieldsOnly: Boolean): string;
var
  lFieldInfo: TFieldInfo;
  lParts: string;
  lFirst: Boolean;
begin
  lParts := '';
  lFirst := True;
  if (not ARefreshFieldsOnly) and
     (foAutoGenerated in TableMap.fPrimaryKeyOptions) and
     (not TableMap.fPrimaryKeyFieldName.IsEmpty) then
  begin
    lParts := 'inserted.' + GetFieldNameForSQL(TableMap.fPrimaryKeyFieldName);
    lFirst := False;
  end;
  for lFieldInfo in TableMap.RefreshFields do
  begin
    if lFirst then
    begin
      lParts := 'inserted.' + GetFieldNameForSQL(lFieldInfo.FieldName);
      lFirst := False;
    end
    else
      lParts := lParts + ', inserted.' + GetFieldNameForSQL(lFieldInfo.FieldName);
  end;
  if lParts = '' then
    Result := ''
  else
    Result := ' OUTPUT ' + lParts;
end;

function TMVCSQLGeneratorMSSQL.CreateInsertSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lKeyValue: TPair<TRttiField, TFieldInfo>;
  lSB: TStringBuilder;
  lPKInInsert: Boolean;
  lFieldName: String;
  lOutput: string;
  lValuesPos: Integer;
  lLegacyPos: Integer;
begin
  lPKInInsert := (not TableMap.fPrimaryKeyFieldName.IsEmpty) and (not(TMVCActiveRecordFieldOption.foAutoGenerated in TableMap.fPrimaryKeyOptions));
  lPKInInsert := lPKInInsert and (not(TMVCActiveRecordFieldOption.foReadOnly in TableMap.fPrimaryKeyOptions));
  lSB := TStringBuilder.Create;
  try
    lSB.Append('INSERT INTO ' + TableMap.fTableName + '(');
    if lPKInInsert then
    begin
      lSB.Append(TableMap.fPrimaryKeyFieldName + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(GetFieldNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.Insertable then
      begin
        lSB.Append(lKeyValue.Value.FieldName + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(') values (');
    if lPKInInsert then
    begin
      lSB.Append(':' + TableMap.fPrimaryKeyFieldName + ',');
    end;

    {partition}
    for lFieldName in fPartitionInfo.FieldNames do
    begin
      lSB.Append(':' + GetParamNameForSQL(lFieldName) + ',');
    end;
    {end-partition}

    for lKeyValue in TableMap.fMap do
    begin
      if lKeyValue.Value.IsVersion then
      begin
        lSB.Append(OBJECT_VERSION_STARTING_VALUE + ',');
      end else if lKeyValue.Value.Insertable then
      begin
        lSB.Append(':' + lKeyValue.Value.FieldName + ',');
      end;
    end;
    lSB.Remove(lSB.Length - 1, 1);
    lSB.Append(')');
    Result := lSB.ToString;
  finally
    lSB.Free;
  end;

  // Strip any legacy ;SELECT SCOPE_IDENTITY tail that may have been added
  lLegacyPos := Pos(';SELECT SCOPE_IDENTITY', UpperCase(Result));
  if lLegacyPos > 0 then
    Result := TrimRight(Copy(Result, 1, lLegacyPos - 1));

  // Build OUTPUT clause (PK + RefreshFields for INSERT)
  lOutput := BuildOutputClause(TableMap, False);
  if lOutput = '' then
    Exit;

  // Inject OUTPUT before " VALUES " (case-insensitive search, preserve original case)
  lValuesPos := Pos(' VALUES (', UpperCase(Result));
  if lValuesPos > 0 then
    Insert(lOutput, Result, lValuesPos);
end;

function TMVCSQLGeneratorMSSQL.CreateUpdateSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord): string;
var
  lOutput: string;
  lWherePos: Integer;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance);
  if TableMap.RefreshFields.Count = 0 then
    Exit;

  // RefreshFields-only for UPDATE (PK is already known, including it causes ExecSQL errors)
  lOutput := BuildOutputClause(TableMap, True);
  if lOutput = '' then
    Exit;

  // Inject OUTPUT before " where " — the base class uses lowercase " where "
  lWherePos := Pos(' WHERE ', UpperCase(Result));
  if lWherePos > 0 then
    Insert(lOutput, Result, lWherePos);
end;

function TMVCSQLGeneratorMSSQL.CreateUpdateSQL(
  const TableMap: TMVCTableMap;
  const ARInstance: TMVCActiveRecord;
  const ADirtyFields: TArray<string>): string;
var
  lOutput: string;
  lWherePos: Integer;
begin
  Result := inherited CreateUpdateSQL(TableMap, ARInstance, ADirtyFields);
  if TableMap.RefreshFields.Count = 0 then
    Exit;

  // RefreshFields-only for UPDATE (PK is already known, including it causes ExecSQL errors)
  lOutput := BuildOutputClause(TableMap, True);
  if lOutput = '' then
    Exit;

  // Inject OUTPUT before " where " — the base class uses lowercase " where "
  lWherePos := Pos(' WHERE ', UpperCase(Result));
  if lWherePos > 0 then
    Insert(lOutput, Result, lWherePos);
end;

function TMVCSQLGeneratorMSSQL.BuildSoftDeleteWhereSuffix(const TableMap: TMVCTableMap): string;
begin
  Result := inherited BuildSoftDeleteWhereSuffix(TableMap);
  // MSSQL has no FALSE keyword in default contexts; use 0 for BIT comparison.
  Result := StringReplace(Result, ' = FALSE', ' = 0', [rfIgnoreCase]);
end;

function TMVCSQLGeneratorMSSQL.BuildSoftDeleteSetDeleted(const TableMap: TMVCTableMap): string;
begin
  Result := inherited BuildSoftDeleteSetDeleted(TableMap);
  // MSSQL BIT columns: TRUE -> 1
  Result := StringReplace(Result, ' = TRUE', ' = 1', [rfIgnoreCase]);
end;

function TMVCSQLGeneratorMSSQL.BuildSoftDeleteSetRestored(const TableMap: TMVCTableMap): string;
begin
  Result := inherited BuildSoftDeleteSetRestored(TableMap);
  // MSSQL BIT columns: FALSE -> 0
  Result := StringReplace(Result, ' = FALSE', ' = 0', [rfIgnoreCase]);
end;

function TMVCSQLGeneratorMSSQL.GetCompilerClass: TRQLCompilerClass;
begin
  Result := TRQLMSSQLCompiler;
end;

initialization

TMVCSQLGeneratorRegistry.Instance.RegisterSQLGenerator('mssql', TMVCSQLGeneratorMSSQL);

finalization

TMVCSQLGeneratorRegistry.Instance.UnRegisterSQLGenerator('mssql');

end.
