{******************************************************************************}
{                                                                              }
{  Delphi SwagDoc Library                                                      }
{  Copyright (c) 2018 Marcelo Jaloto                                           }
{  https://github.com/marcelojaloto/SwagDoc                                    }
{                                                                              }
{******************************************************************************}
{                                                                              }
{  Licensed under the Apache License, Version 2.0 (the "License");             }
{  you may not use this file except in compliance with the License.            }
{  You may obtain a copy of the License at                                     }
{                                                                              }
{      http://www.apache.org/licenses/LICENSE-2.0                              }
{                                                                              }
{  Unless required by applicable law or agreed to in writing, software         }
{  distributed under the License is distributed on an "AS IS" BASIS,           }
{  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    }
{  See the License for the specific language governing permissions and         }
{  limitations under the License.                                              }
{                                                                              }
{******************************************************************************}

unit Swag.Doc.SecurityDefinitionHttp;

interface

uses
  System.SysUtils,
  System.JSON,
  Swag.Common.Types,
  Swag.Doc.SecurityDefinition;

type
  /// <summary>
  /// The security scheme object for the HTTP authentication schemes defined by RFC7235, such as basic, bearer or digest.
  /// It is available in OpenAPI 3 only. When a Swagger 2.0 document is generated the basic scheme is written as
  /// the basic security definition and any other scheme is written as an API key sent in the Authorization header.
  /// </summary>
  [ASecurityDefinition(ssdHttp)]
  TSwagSecurityDefinitionHttp = class(TSwagSecurityDefinition)
  private
    fScheme: string;
    fBearerFormat: string;
  protected
    function GetTypeSecurity: TSwagSecurityDefinitionType; override;
  public
    function GenerateJsonObject: TJSONObject; overload; override;
    function GenerateJsonObject(const pVersion: TSwagVersion): TJSONObject; overload; override;
    procedure Load(pJson: TJSONObject); overload; override;
    procedure Load(pJson: TJSONObject; const pVersion: TSwagVersion); overload; override;

    /// <summary>
    /// Required. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235.
    /// The values used SHOULD be registered in the IANA Authentication Scheme registry, for example "basic" or "bearer".
    /// </summary>
    property Scheme: string read fScheme write fScheme;

    /// <summary>
    /// A hint to the client to identify how the bearer token is formatted, for example "JWT".
    /// Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
    /// </summary>
    property BearerFormat: string read fBearerFormat write fBearerFormat;
  end;

implementation

uses
  System.Classes,
  Swag.Common.Consts;

const
  c_SwagSecurityDefinitionHttpType = 'type';
  c_SwagSecurityDefinitionHttpDescription = 'description';
  c_SwagSecurityDefinitionHttpScheme = 'scheme';
  c_SwagSecurityDefinitionHttpBearerFormat = 'bearerFormat';
  c_SwagSecurityDefinitionHttpIn = 'in';
  c_SwagSecurityDefinitionHttpName = 'name';
  c_SwagSecurityDefinitionHttpSchemeBasic = 'basic';
  c_SwagSecurityDefinitionHttpInHeader = 'header';
  c_SwagSecurityDefinitionHttpAuthorizationHeader = 'Authorization';

{ TSwagSecurityDefinitionHttp }

function TSwagSecurityDefinitionHttp.GenerateJsonObject: TJSONObject;
begin
  Result := TJSONObject.Create;
  if SameText(fScheme, c_SwagSecurityDefinitionHttpSchemeBasic) then
    Result.AddPair(c_SwagSecurityDefinitionHttpType, c_SwagSecurityDefinitionType[ssdBasic])
  else
  begin
    Result.AddPair(c_SwagSecurityDefinitionHttpType, c_SwagSecurityDefinitionType[ssdApiKey]);
    Result.AddPair(c_SwagSecurityDefinitionHttpIn, c_SwagSecurityDefinitionHttpInHeader);
    Result.AddPair(c_SwagSecurityDefinitionHttpName, c_SwagSecurityDefinitionHttpAuthorizationHeader);
  end;
  if fDescription.Length > 0 then
    Result.AddPair(c_SwagSecurityDefinitionHttpDescription, fDescription);
end;

function TSwagSecurityDefinitionHttp.GenerateJsonObject(const pVersion: TSwagVersion): TJSONObject;
begin
  if pVersion <> svOpenApi3 then
    Exit(GenerateJsonObject);

  Result := TJSONObject.Create;
  Result.AddPair(c_SwagSecurityDefinitionHttpType, ReturnTypeSecurityToString);
  if fDescription.Length > 0 then
    Result.AddPair(c_SwagSecurityDefinitionHttpDescription, fDescription);
  Result.AddPair(c_SwagSecurityDefinitionHttpScheme, fScheme);
  if fBearerFormat.Length > 0 then
    Result.AddPair(c_SwagSecurityDefinitionHttpBearerFormat, fBearerFormat);
end;

function TSwagSecurityDefinitionHttp.GetTypeSecurity: TSwagSecurityDefinitionType;
begin
  Result := ssdHttp;
end;

procedure TSwagSecurityDefinitionHttp.Load(pJson: TJSONObject);
begin
  if Assigned(pJson.Values[c_SwagSecurityDefinitionHttpDescription]) then
    fDescription := pJson.Values[c_SwagSecurityDefinitionHttpDescription].Value;
  if Assigned(pJson.Values[c_SwagSecurityDefinitionHttpScheme]) then
    fScheme := pJson.Values[c_SwagSecurityDefinitionHttpScheme].Value
  else if Assigned(pJson.Values[c_SwagSecurityDefinitionHttpType]) and
    SameText(pJson.Values[c_SwagSecurityDefinitionHttpType].Value, c_SwagSecurityDefinitionType[ssdBasic]) then
    fScheme := c_SwagSecurityDefinitionHttpSchemeBasic;
end;

procedure TSwagSecurityDefinitionHttp.Load(pJson: TJSONObject; const pVersion: TSwagVersion);
begin
  Load(pJson);
  if Assigned(pJson.Values[c_SwagSecurityDefinitionHttpBearerFormat]) then
    fBearerFormat := pJson.Values[c_SwagSecurityDefinitionHttpBearerFormat].Value;
end;

initialization
  RegisterClass(TSwagSecurityDefinitionHttp);

end.
