// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// ISAPI extension variant of the test server. Built as a shared library
// (TestServerISAPI.dll on Windows) and hosted by IIS Express through a
// wildcard script-map handler configured by tasks.py at test time.
//
// applicationhost.config handler mapping (generated by tasks.py):
//
//   <handlers accessPolicy="Read, Execute, Script">
//     <add name="DMVCISAPI" path="*" verb="*"
//          modules="IsapiModule"
//          scriptProcessor="C:\...\TestServerISAPI.dll"
//          resourceType="Unspecified"
//          requireAccess="None"/>
//   </handlers>
//
// ***************************************************************************

library TestServerISAPI;

uses
  Winapi.ActiveX,
  Winapi.Windows,
  System.Win.ComObj,
  MVCFramework.Logger,
  MVCFramework.Commons,
  MVCFramework.Serializer.Commons,
  MVCFramework.Serializer.Text in '..\..\..\sources\MVCFramework.Serializer.Text.pas',
  MVCFramework.Serializer.HTML in '..\..\..\sources\MVCFramework.Serializer.HTML.pas',
  Web.WebBroker,
  Web.Win.ISAPIApp,
  Web.Win.ISAPIThreadPool,
  WebModuleUnit in 'WebModuleUnit.pas' {MainWebModule: TWebModule},
  TestServerControllerU in 'TestServerControllerU.pas',
  TestServerControllerExceptionU in 'TestServerControllerExceptionU.pas',
  SpeedMiddlewareU in 'SpeedMiddlewareU.pas',
  TestServerControllerPrivateU in 'TestServerControllerPrivateU.pas',
  AuthHandlersU in 'AuthHandlersU.pas',
  BusinessObjectsU in '..\..\..\samples\commons\BusinessObjectsU.pas',
  TestServerControllerJSONRPCU in 'TestServerControllerJSONRPCU.pas',
  RandomUtilsU in '..\..\..\samples\commons\RandomUtilsU.pas',
  MVCFramework.Tests.Serializer.Entities in '..\..\common\MVCFramework.Tests.Serializer.Entities.pas',
  FDConnectionConfigU in '..\..\common\FDConnectionConfigU.pas',
  Entities in '..\TestClient\Entities.pas',
  EntitiesProcessors in '..\TestClient\EntitiesProcessors.pas',
  MVCFramework.JSONRPC.Client in '..\..\..\sources\MVCFramework.JSONRPC.Client.pas',
  MVCFramework.JSONRPC in '..\..\..\sources\MVCFramework.JSONRPC.pas',
  MVCFramework in '..\..\..\sources\MVCFramework.pas';

function TerminateExtension(dwFlags: DWORD): BOOL; stdcall;
begin
  ReleaseGlobalLogger;
  Result := Web.Win.ISAPIThreadPool.TerminateExtension(dwFlags);
end;

exports
  GetExtensionVersion,
  HttpExtensionProc,
  TerminateExtension;

begin
  CoInitFlags := COINIT_MULTITHREADED;

  // DMVCFramework specific configurations
  MVCSerializeNulls := True;
  // Match the same Sqids alphabet used by the other TestServer variants so
  // that ID-encoding tests stay consistent across all test fixtures.
  TMVCSqids.SQIDS_ALPHABET := 'axDlw8dRnsPCrbZIAEMFG4TQ6gc3iWtOy9v5NBz0LfSmuKV71JHkUhYpej2Xqo';
  TMVCSqids.SQIDS_MIN_LENGTH := 6;

  Application.Initialize;
  Application.WebModuleClass := WebModuleClass;
  Application.Run;
end.
