unit ModelsU;

// ===========================================================================
//  Demo model: two validation layers on two distinct classes.
//
//  The classic DMVCFramework split:
//
//    TPersonDTO  - plain class inheriting TMVCValidatable.
//                  Validators sit on PROPERTIES. They fire at the HTTP
//                  boundary, during deserialization, inside
//                  TMVCValidationEngine.ValidateAndRaise. Failure raises
//                  EMVCValidationException (422).
//
//    TPerson     - AR entity inheriting TMVCActiveRecord.
//                  Validators sit on the backing FIELDS, plus an
//                  OnStorageValidate override for business invariants.
//                  They fire inside Insert / Update. Failure raises
//                  EMVCStorageValidationException (422, distinct class).
//
//  The DTO NEVER reaches the database; the AR NEVER reaches the HTTP
//  boundary. No validator fires twice. The layer that rejected a payload
//  is identified by the exception class, not by a new body field.
// ===========================================================================

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Validation,
  MVCFramework.Validators,
  MVCFramework.Nullables;

type
  // ---- Input layer ---------------------------------------------------------
  [MVCNameCase(ncCamelCase)]
  TPersonDTO = class(TMVCValidatable)
  private
    FName: string;
    FEmail: string;
  public
    // Property-level validators: loose "shape" checks enforced at the
    // HTTP boundary, before the action even runs.
    [MVCRequired('name is required')]
    property Name: string read FName write FName;

    [MVCRequired('email is required')]
    property Email: string read FEmail write FEmail;
  end;

  // ---- Storage layer -------------------------------------------------------
  [MVCNameCase(ncCamelCase)]
  [MVCTable('people')]
  TPerson = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    fID: NullableInt32;

    // Field-level validators: stricter format / length checks enforced at
    // save time. They run inside Insert / Update, never at the HTTP
    // boundary (the AR class is not the [MVCFromBody] parameter).
    [MVCTableField('name')]
    [MVCRequired('name is required')]
    [MVCMinLength(2, 'name must be at least 2 chars')]
    fName: NullableString;

    [MVCTableField('email')]
    [MVCRequired('email is required')]
    [MVCEmail('email must be a valid address')]
    fEmail: NullableString;
  protected
    procedure OnStorageValidate(const AErrors: PMVCValidationErrors;
      const EntityAction: TMVCEntityAction); override;
  public
    property ID: NullableInt32 read fID write fID;
    property Name: NullableString read fName write fName;
    property Email: NullableString read fEmail write fEmail;
  end;

implementation

uses
  System.SysUtils;

procedure TPerson.OnStorageValidate(const AErrors: PMVCValidationErrors;
  const EntityAction: TMVCEntityAction);
begin
  // Storage-only policy: the email domain must be @example.com. Encoding
  // it as an attribute would be possible but this rule is a business
  // invariant, not a data-format constraint - so it lives here.
  if fEmail.HasValue and
     (not LowerCase(fEmail.Value).EndsWith('@example.com')) then
  begin
    AErrors.Add('email',
      'email domain must be @example.com (storage policy)');
  end;
end;

end.
