// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

unit ActiveRecordQuickWinsTestsU;

interface

uses
  DUnitX.TestFramework,
  System.SysUtils, System.Classes,
  System.Generics.Collections,
  Data.DB,
  FireDAC.Comp.Client, FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.DApt,
  FireDAC.Comp.DataSet,
  FireDAC.Phys.SQLite, FireDAC.Phys.SQLiteWrapper.Stat,
  MVCFramework.ActiveRecord, MVCFramework.SQLGenerators.Sqlite,
  MVCFramework.Nullables;

type
  [MVCTable('orders_notrack')]
  TOrderNoTrack = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('total')]
    FTotal: Currency;
  public
    property ID: Int64 read FID write FID;
    property Total: Currency read FTotal write FTotal;
  end;

  [MVCTable('orders')]
  [MVCDirtyTracking]
  TOrderDT = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('total')]
    FTotal: Currency;
    [MVCTableField('notes')]
    FNotes: string;
  public
    property ID: Int64 read FID write FID;
    property Total: Currency read FTotal write FTotal;
    property Notes: string read FNotes write FNotes;
  end;

  [MVCTable('customers_sd')]
  TCustomerSDTimestamp = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('name')]
    FName: string;
    [MVCTableField('deleted_at')]
    [MVCSoftDeleted]
    FDeletedAt: NullableTDateTime;
  public
    property ID: Int64 read FID write FID;
    property Name: string read FName write FName;
    property DeletedAt: NullableTDateTime read FDeletedAt write FDeletedAt;
  end;

  [MVCTable('orders_sd')]
  TOrderSDFlag = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('description')]
    FDescription: string;
    [MVCTableField('is_deleted')]
    [MVCSoftDeleted]
    FIsDeleted: Boolean;
  public
    property ID: Int64 read FID write FID;
    property Description: string read FDescription write FDescription;
    property IsDeletedFlag: Boolean read FIsDeleted write FIsDeleted;
  end;

  [TestFixture]
  TTestSoftDelete = class
  strict private
    FConn: TFDConnection;
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestSoftDeleteTimestampSetsField;
    [Test]     procedure TestSoftDeleteFlagSetsField;
    [Test]     procedure TestSelectAutoFiltersDeleted;
    [Test]     procedure TestIncludeSoftDeletedScopeReturnsAll;
  end;

  [TestFixture]
  TTestDirtyTracking = class
  strict private
    FConn: TFDConnection;
    procedure SeedRow(out AID: Int64);
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestNotDirtyAfterLoad;
    [Test]     procedure TestDirtyAfterFieldChange;
    [Test]     procedure TestNotDirtyAfterUpdate;
    [Test]     procedure TestGetDirtyFieldsByName;
    [Test]     procedure TestIsDirtyByFieldName;
    [Test]     procedure TestUpdateEmitsOnlyDirtyColumns;
    [Test]     procedure TestUpdateIfDirtySkipsWhenClean;
    [Test]     procedure TestUpdateIfDirtyExecutesWhenDirty;
    [Test]     procedure TestUpdateIfDirtyRaisesOnNonTrackedClass;
  end;

implementation

procedure TTestDirtyTracking.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  FConn.ExecSQL(
    'CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'total NUMERIC, notes TEXT)');
  FConn.ExecSQL(
    'CREATE TABLE orders_notrack (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'total NUMERIC)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestDirtyTracking.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestDirtyTracking.SeedRow(out AID: Int64);
var
  lOrder: TOrderDT;
begin
  lOrder := TOrderDT.Create;
  try
    lOrder.Total := 100.0;
    lOrder.Notes := 'initial';
    lOrder.Insert;
    AID := lOrder.ID;
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestNotDirtyAfterLoad;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    Assert.IsFalse(lOrder.IsDirty, 'Just-loaded record must not be dirty');
    Assert.AreEqual<NativeInt>(0, Length(lOrder.GetDirtyFields), 'No fields should be dirty');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestDirtyAfterFieldChange;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Total := 200.0;
    Assert.IsTrue(lOrder.IsDirty, 'After change, IsDirty must be True');
    Assert.IsTrue(lOrder.IsDirty('total'), 'Total must be flagged dirty');
    Assert.IsFalse(lOrder.IsDirty('notes'), 'Notes was not changed; must not be dirty');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestNotDirtyAfterUpdate;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Total := 200.0;
    lOrder.Update;
    Assert.IsFalse(lOrder.IsDirty,
      'After successful Update, snapshot must be rehashed - not dirty');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestGetDirtyFieldsByName;
var
  lID: Int64;
  lOrder: TOrderDT;
  lDirty: TArray<string>;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Total := 200.0;
    lOrder.Notes := 'changed';
    lDirty := lOrder.GetDirtyFields;
    Assert.AreEqual<NativeInt>(2, Length(lDirty), 'Both fields dirty');
    // Order is map-iteration dependent; assert membership not order
    Assert.IsTrue(
      ((lDirty[0] = 'total') and (lDirty[1] = 'notes')) or
      ((lDirty[0] = 'notes') and (lDirty[1] = 'total')),
      'Both total and notes must appear in dirty list');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestIsDirtyByFieldName;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Notes := 'changed only';
    Assert.IsTrue(lOrder.IsDirty('notes'), 'notes must be dirty');
    Assert.IsFalse(lOrder.IsDirty('total'), 'total must not be dirty');
    Assert.IsFalse(lOrder.IsDirty('nonexistent_field'),
      'Non-existent field returns False, not exception');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestUpdateEmitsOnlyDirtyColumns;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Notes := 'changed only';
    lOrder.Update;
  finally
    lOrder.Free;
  end;
  // Verify total is unchanged and notes is updated
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    Assert.AreEqual(Currency(100), lOrder.Total, 'Total must NOT have been touched');
    Assert.AreEqual('changed only', lOrder.Notes, 'Notes must have been written');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestUpdateIfDirtySkipsWhenClean;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.UpdateIfDirty;  // should early-return — nothing changed
    Assert.IsFalse(lOrder.IsDirty, 'Record must remain clean after UpdateIfDirty no-op');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestUpdateIfDirtyExecutesWhenDirty;
var
  lID: Int64;
  lOrder: TOrderDT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    lOrder.Notes := 'changed';
    lOrder.UpdateIfDirty;
    Assert.IsFalse(lOrder.IsDirty, 'After UpdateIfDirty the snapshot must be rebuilt');
  finally
    lOrder.Free;
  end;
  lOrder := TMVCActiveRecord.GetByPK<TOrderDT>(lID);
  try
    Assert.AreEqual('changed', lOrder.Notes, 'Persisted value must reflect the change');
  finally
    lOrder.Free;
  end;
end;

procedure TTestDirtyTracking.TestUpdateIfDirtyRaisesOnNonTrackedClass;
begin
  Assert.WillRaise(
    procedure
    var
      lO: TOrderNoTrack;
    begin
      lO := TOrderNoTrack.Create;
      try
        lO.UpdateIfDirty;
      finally
        lO.Free;
      end;
    end,
    EMVCActiveRecord);
end;

{ TTestSoftDelete }

procedure TTestSoftDelete.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  FConn.ExecSQL(
    'CREATE TABLE customers_sd (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'name TEXT, deleted_at TEXT)');
  FConn.ExecSQL(
    'CREATE TABLE orders_sd (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'description TEXT, is_deleted INTEGER DEFAULT 0)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestSoftDelete.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestSoftDelete.TestSoftDeleteTimestampSetsField;
var
  lC: TCustomerSDTimestamp;
  lQry: TFDQuery;
  lDeletedAtAfter: string;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alice';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT deleted_at FROM customers_sd WHERE name = :n';
    lQry.ParamByName('n').AsString := 'Alice';
    lQry.Open;
    lDeletedAtAfter := lQry.FieldByName('deleted_at').AsString;
    Assert.IsFalse(lDeletedAtAfter.IsEmpty, 'deleted_at must be populated after soft-delete');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestSoftDeleteFlagSetsField;
var
  lO: TOrderSDFlag;
  lQry: TFDQuery;
begin
  lO := TOrderSDFlag.Create;
  try
    lO.Description := 'Test';
    lO.Insert;
    lO.Delete;
  finally
    lO.Free;
  end;
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT is_deleted FROM orders_sd WHERE description = :d';
    lQry.ParamByName('d').AsString := 'Test';
    lQry.Open;
    Assert.IsTrue(lQry.FieldByName('is_deleted').AsInteger <> 0,
      'is_deleted must be non-zero (true) after soft-delete');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectAutoFiltersDeleted;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alive';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Deleted';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lList := TMVCActiveRecord.All<TCustomerSDTimestamp>;
  try
    Assert.AreEqual<NativeInt>(1, lList.Count, 'Default scope must filter out soft-deleted rows');
    Assert.AreEqual('Alive', lList[0].Name);
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestIncludeSoftDeletedScopeReturnsAll;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alive2';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Deleted2';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  TMVCActiveRecord.IncludeSoftDeleted(True);
  try
    lList := TMVCActiveRecord.All<TCustomerSDTimestamp>;
    try
      Assert.AreEqual<NativeInt>(2, lList.Count,
        'IncludeSoftDeleted scope must return all rows including deleted');
    finally
      lList.Free;
    end;
  finally
    TMVCActiveRecord.IncludeSoftDeleted(False);
  end;
end;

initialization
  TDUnitX.RegisterTestFixture(TTestSoftDelete);
  TDUnitX.RegisterTestFixture(TTestDirtyTracking);

end.
