// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************

unit ActiveRecordQuickWinsTestsU;

interface

uses
  DUnitX.TestFramework,
  System.SysUtils, System.Classes,
  System.Generics.Collections,
  Data.DB,
  FireDAC.Comp.Client, FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.DApt,
  FireDAC.Comp.DataSet,
  FireDAC.Phys.SQLite, FireDAC.Phys.SQLiteWrapper.Stat,
  MVCFramework.ActiveRecord, MVCFramework.SQLGenerators.Sqlite,
  MVCFramework.Nullables;

type
  [MVCTable('orders_notrack')]
  TOrderNoTrack = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('total')]
    FTotal: Currency;
  public
    property ID: Int64 read FID write FID;
    property Total: Currency read FTotal write FTotal;
  end;

  [MVCTable('orders')]
  [MVCChangeTracking]
  TOrderCT = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('total')]
    FTotal: Currency;
    [MVCTableField('notes')]
    FNotes: string;
    class var FExecutedSQLCount: Integer;
  protected
    // Spy hook: counts non-query SQL (INSERT / UPDATE / DELETE) executed
    // through this class. Tests use it to assert that UpdateIfChanged on
    // a clean row issues NO SQL. SELECTs go through OnBeforeExecuteQuerySQL,
    // which we don't override - so GetByPK does NOT bump the counter.
    procedure OnBeforeExecuteSQL(var SQL: string); override;
  public
    property ID: Int64 read FID write FID;
    property Total: Currency read FTotal write FTotal;
    property Notes: string read FNotes write FNotes;
    class property ExecutedSQLCount: Integer
      read FExecutedSQLCount write FExecutedSQLCount;
  end;

  [MVCTable('customers_sd')]
  TCustomerSDTimestamp = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('name')]
    FName: string;
    [MVCTableField('deleted_at')]
    [MVCSoftDeleted]
    FDeletedAt: NullableTDateTime;
  public
    property ID: Int64 read FID write FID;
    property Name: string read FName write FName;
    property DeletedAt: NullableTDateTime read FDeletedAt write FDeletedAt;
  end;

  // ---------------------------------------------------------------
  // foRefresh — entities used by TTestForefresh.
  //
  // foRefresh declares "after Insert/Update, re-SELECT this column from
  // the DB so any server-side transformation (trigger, computed column,
  // identity-style adjustment) is reflected back into the in-memory
  // instance". The field stays fully writable.
  //
  // TRefreshable models the canonical use case: a trigger writes a
  // derived value into `upper_name` whenever `name` is changed.
  //   * `name`        - user-controlled, written verbatim
  //   * `upper_name`  - foRefresh, populated by the trigger to UPPER(name)
  //   * `notes`       - foRefresh, written verbatim by the user — proves
  //                     that foRefresh on an untransformed column simply
  //                     round-trips (no spurious NULL-ing).
  // ---------------------------------------------------------------
  [MVCTable('refreshable')]
  TRefreshable = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('name')]
    FName: string;
    // Computed column — read-only for the framework, refreshed via
    // RETURNING after every INSERT / UPDATE so the in-memory instance
    // mirrors the DB-computed value.
    [MVCTableField('upper_name', [foReadOnly, foRefresh])]
    FUpperName: NullableString;
    // Plain writable column also marked foRefresh - exercises the
    // "writable + refetch" combination (no transformation, just a
    // round-trip via RETURNING).
    [MVCTableField('notes', [foRefresh])]
    FNotes: NullableString;
  public
    property ID: Int64 read FID write FID;
    property Name: string read FName write FName;
    property UpperName: NullableString read FUpperName write FUpperName;
    property Notes: NullableString read FNotes write FNotes;
  end;

  [MVCTable('orders_sd')]
  TOrderSDFlag = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('description')]
    FDescription: string;
    [MVCTableField('is_deleted')]
    [MVCSoftDeleted]
    FIsDeleted: Boolean;
  public
    property ID: Int64 read FID write FID;
    property Description: string read FDescription write FDescription;
    property IsDeletedFlag: Boolean read FIsDeleted write FIsDeleted;
  end;

  [TestFixture]
  TTestSoftDelete = class
  strict private
    FConn: TFDConnection;
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestSoftDeleteTimestampSetsField;
    [Test]     procedure TestSoftDeleteFlagSetsField;
    [Test]     procedure TestSelectAutoFiltersDeleted;
    [Test]     procedure TestIncludeSoftDeletedScopeReturnsAll;
    [Test]     procedure TestIsDeletedTimestamp;
    [Test]     procedure TestIsDeletedFlag;
    [Test]     procedure TestRestore;
    [Test]     procedure TestRestoreOnNonSoftRaises;
    [Test]     procedure TestRestoreOnAliveRaises;
    [Test]     procedure TestHardDeleteBypassesSoftDelete;
    [Test]     procedure TestHardDeleteRQLBulk;
    [Test]     procedure TestRestoreRQLBulk;
    [Test]     procedure TestDeleteRQLDispatchesSoftDelete;
    [Test]     procedure TestSelectRQLAutoFiltersDeleted;
    [Test]     procedure TestSelectRQLWithLimitAutoFiltersDeleted;
    [Test]     procedure TestSelectRQLEmptyAutoFilter;
    [Test]     procedure TestSelectRQLBypassedByIncludeSoftDeleted;
  end;

  [TestFixture]
  TTestChangeTracking = class
  strict private
    FConn: TFDConnection;
    procedure SeedRow(out AID: Int64);
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestNotChangedAfterLoad;
    [Test]     procedure TestChangedAfterFieldChange;
    [Test]     procedure TestNotChangedAfterUpdate;
    [Test]     procedure TestGetChangedFieldsByName;
    [Test]     procedure TestIsChangedByFieldName;
    [Test]     procedure TestUpdateEmitsOnlyChangedColumns;
    [Test]     procedure TestUpdateIfChangedSkipsWhenClean;
    [Test]     procedure TestUpdateIfChangedExecutesWhenChanged;
    [Test]     procedure TestUpdateIfChangedRaisesOnNonTrackedClass;
  end;

  // ---------------------------------------------------------------
  // IsNew / IsPersisted — entities used by TTestIsNew. Two flavours of
  // PK to exercise both code paths in TryGetPKValue:
  //
  //   * NullableInt64 PK -> "no value" branch (HasValue=False)
  //   * plain Int64 PK   -> "default-constructed" branch (Value=0)
  // ---------------------------------------------------------------
  [MVCTable('isnew_nullable')]
  TIsNewNullablePK = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: NullableInt64;
    [MVCTableField('name')]
    FName: string;
  public
    property ID: NullableInt64 read FID write FID;
    property Name: string read FName write FName;
  end;

  [MVCTable('isnew_plain')]
  TIsNewPlainPK = class(TMVCActiveRecord)
  strict private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;
    [MVCTableField('name')]
    FName: string;
  public
    property ID: Int64 read FID write FID;
    property Name: string read FName write FName;
  end;

  [TestFixture]
  TTestIsNew = class
  strict private
    FConn: TFDConnection;
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestFreshInstanceWithNullablePKIsNew;
    [Test]     procedure TestFreshInstanceWithPlainPKIsNew;
    [Test]     procedure TestAfterInsertNotNew;
    [Test]     procedure TestAfterLoadNotNew;
    [Test]     procedure TestIsPersistedIsNegationOfIsNew;
  end;

  [TestFixture]
  TTestForefresh = class
  strict private
    FConn: TFDConnection;
  public
    [SetUp]    procedure SetUp;
    [TearDown] procedure TearDown;
    [Test]     procedure TestInsertRefetchesTriggerOutput;
    [Test]     procedure TestUpdateRefetchesTriggerOutput;
    [Test]     procedure TestForefreshFieldStaysWritable;
    [Test]     procedure TestPKAndForefreshBothFilled;
  end;

implementation

procedure TOrderCT.OnBeforeExecuteSQL(var SQL: string);
begin
  inherited;
  Inc(FExecutedSQLCount);
end;

procedure TTestChangeTracking.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  FConn.ExecSQL(
    'CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'total NUMERIC, notes TEXT)');
  FConn.ExecSQL(
    'CREATE TABLE orders_notrack (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'total NUMERIC)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestChangeTracking.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestChangeTracking.SeedRow(out AID: Int64);
var
  lOrder: TOrderCT;
begin
  lOrder := TOrderCT.Create;
  try
    lOrder.Total := 100.0;
    lOrder.Notes := 'initial';
    lOrder.Insert;
    AID := lOrder.ID;
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestNotChangedAfterLoad;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    Assert.IsFalse(lOrder.IsChanged, 'Just-loaded record must not be flagged as changed');
    Assert.AreEqual<NativeInt>(0, Length(lOrder.GetChangedFields), 'No fields should be flagged as changed');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestChangedAfterFieldChange;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    lOrder.Total := 200.0;
    Assert.IsTrue(lOrder.IsChanged, 'After change, IsChanged must be True');
    Assert.IsTrue(lOrder.IsChanged('total'), 'Total must be flagged as changed');
    Assert.IsFalse(lOrder.IsChanged('notes'), 'Notes was not modified; must not be flagged');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestNotChangedAfterUpdate;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    lOrder.Total := 200.0;
    lOrder.Update;
    Assert.IsFalse(lOrder.IsChanged,
      'After successful Update, snapshot must be rehashed - no longer flagged');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestGetChangedFieldsByName;
var
  lID: Int64;
  lOrder: TOrderCT;
  lChanged: TArray<string>;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    lOrder.Total := 200.0;
    lOrder.Notes := 'changed';
    lChanged := lOrder.GetChangedFields;
    Assert.AreEqual<NativeInt>(2, Length(lChanged), 'Both fields must be flagged');
    // Order is map-iteration dependent; assert membership not order
    Assert.IsTrue(
      ((lChanged[0] = 'total') and (lChanged[1] = 'notes')) or
      ((lChanged[0] = 'notes') and (lChanged[1] = 'total')),
      'Both total and notes must appear in the changed list');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestIsChangedByFieldName;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    lOrder.Notes := 'changed only';
    Assert.IsTrue(lOrder.IsChanged('notes'), 'notes must be flagged');
    Assert.IsFalse(lOrder.IsChanged('total'), 'total must not be flagged');
    Assert.IsFalse(lOrder.IsChanged('nonexistent_field'),
      'Non-existent field returns False, not exception');
    // FieldName lookup is case-insensitive (uses SameText).
    Assert.IsTrue(lOrder.IsChanged('NOTES'), 'lookup must be case-insensitive');
    Assert.IsTrue(lOrder.IsChanged('Notes'), 'lookup must be case-insensitive');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestUpdateEmitsOnlyChangedColumns;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    lOrder.Notes := 'changed only';
    lOrder.Update;
  finally
    lOrder.Free;
  end;
  // Verify total is unchanged and notes is updated
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    Assert.AreEqual(Currency(100), lOrder.Total, 'Total must NOT have been touched');
    Assert.AreEqual('changed only', lOrder.Notes, 'Notes must have been written');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestUpdateIfChangedSkipsWhenClean;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    // Reset the spy AFTER GetByPK so we only measure what UpdateIfChanged
    // does next. The spy counts INSERT / UPDATE / DELETE; SELECTs are not
    // counted (they go through OnBeforeExecuteQuerySQL).
    TOrderCT.ExecutedSQLCount := 0;
    lOrder.UpdateIfChanged;  // should early-return — nothing changed
    Assert.AreEqual<Integer>(0, TOrderCT.ExecutedSQLCount,
      'UpdateIfChanged on a clean row must NOT issue any SQL');
    Assert.IsFalse(lOrder.IsChanged, 'Record must remain clean after UpdateIfChanged no-op');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestUpdateIfChangedExecutesWhenChanged;
var
  lID: Int64;
  lOrder: TOrderCT;
begin
  SeedRow(lID);
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    TOrderCT.ExecutedSQLCount := 0;
    lOrder.Notes := 'changed';
    lOrder.UpdateIfChanged;
    Assert.AreEqual<Integer>(1, TOrderCT.ExecutedSQLCount,
      'UpdateIfChanged must issue exactly one UPDATE when there are changes');
    Assert.IsFalse(lOrder.IsChanged, 'After UpdateIfChanged the snapshot must be rebuilt');
  finally
    lOrder.Free;
  end;
  lOrder := TMVCActiveRecord.GetByPK<TOrderCT>(lID);
  try
    Assert.AreEqual('changed', lOrder.Notes, 'Persisted value must reflect the change');
  finally
    lOrder.Free;
  end;
end;

procedure TTestChangeTracking.TestUpdateIfChangedRaisesOnNonTrackedClass;
begin
  Assert.WillRaise(
    procedure
    var
      lO: TOrderNoTrack;
    begin
      lO := TOrderNoTrack.Create;
      try
        lO.UpdateIfChanged;
      finally
        lO.Free;
      end;
    end,
    EMVCActiveRecord);
end;

{ TTestSoftDelete }

procedure TTestSoftDelete.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  FConn.ExecSQL(
    'CREATE TABLE customers_sd (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'name TEXT, deleted_at TEXT)');
  FConn.ExecSQL(
    'CREATE TABLE orders_sd (id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    'description TEXT, is_deleted INTEGER DEFAULT 0)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestSoftDelete.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestSoftDelete.TestSoftDeleteTimestampSetsField;
var
  lC: TCustomerSDTimestamp;
  lQry: TFDQuery;
  lDeletedAtAfter: string;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alice';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT deleted_at FROM customers_sd WHERE name = :n';
    lQry.ParamByName('n').AsString := 'Alice';
    lQry.Open;
    lDeletedAtAfter := lQry.FieldByName('deleted_at').AsString;
    Assert.IsFalse(lDeletedAtAfter.IsEmpty, 'deleted_at must be populated after soft-delete');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestSoftDeleteFlagSetsField;
var
  lO: TOrderSDFlag;
  lQry: TFDQuery;
begin
  lO := TOrderSDFlag.Create;
  try
    lO.Description := 'Test';
    lO.Insert;
    lO.Delete;
  finally
    lO.Free;
  end;
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT is_deleted FROM orders_sd WHERE description = :d';
    lQry.ParamByName('d').AsString := 'Test';
    lQry.Open;
    Assert.IsTrue(lQry.FieldByName('is_deleted').AsInteger <> 0,
      'is_deleted must be non-zero (true) after soft-delete');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectAutoFiltersDeleted;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alive';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Deleted';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lList := TMVCActiveRecord.All<TCustomerSDTimestamp>;
  try
    Assert.AreEqual<NativeInt>(1, lList.Count, 'Default scope must filter out soft-deleted rows');
    Assert.AreEqual('Alive', lList[0].Name);
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestIncludeSoftDeletedScopeReturnsAll;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alive2';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Deleted2';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  TMVCActiveRecord.IncludeSoftDeleted(True);
  try
    lList := TMVCActiveRecord.All<TCustomerSDTimestamp>;
    try
      Assert.AreEqual<NativeInt>(2, lList.Count,
        'IncludeSoftDeleted scope must return all rows including deleted');
    finally
      lList.Free;
    end;
  finally
    TMVCActiveRecord.IncludeSoftDeleted(False);
  end;
end;

procedure TTestSoftDelete.TestIsDeletedTimestamp;
var
  lC: TCustomerSDTimestamp;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'TestIsDeleted';
    lC.Insert;
    Assert.IsFalse(lC.IsDeleted, 'Just-inserted record must not be deleted');
    lC.Delete;
    Assert.IsTrue(lC.IsDeleted, 'After Delete: IsDeleted must be True');
  finally
    lC.Free;
  end;
end;

procedure TTestSoftDelete.TestIsDeletedFlag;
var
  lO: TOrderSDFlag;
begin
  lO := TOrderSDFlag.Create;
  try
    lO.Description := 'FlagTest';
    lO.Insert;
    Assert.IsFalse(lO.IsDeleted, 'Just-inserted record must not be deleted');
    lO.Delete;
    Assert.IsTrue(lO.IsDeleted, 'After Delete: IsDeleted must be True');
  finally
    lO.Free;
  end;
end;

procedure TTestSoftDelete.TestRestore;
var
  lC: TCustomerSDTimestamp;
  lID: Int64;
  lReloaded: TCustomerSDTimestamp;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'ToRestore';
    lC.Insert;
    lID := lC.ID;
    lC.Delete;
    Assert.IsTrue(lC.IsDeleted, 'After Delete: must be deleted');
    lC.Restore;
    Assert.IsFalse(lC.IsDeleted, 'After Restore: must not be deleted');
  finally
    lC.Free;
  end;
  // Reload and confirm the row is visible in normal scope
  lReloaded := TMVCActiveRecord.GetByPK<TCustomerSDTimestamp>(lID);
  try
    Assert.IsFalse(lReloaded.IsDeleted, 'Reload: row must be visible after Restore');
  finally
    lReloaded.Free;
  end;
end;

procedure TTestSoftDelete.TestRestoreOnNonSoftRaises;
begin
  Assert.WillRaise(
    procedure
    var
      lO: TOrderCT;
    begin
      lO := TOrderCT.Create;
      try
        lO.Restore;
      finally
        lO.Free;
      end;
    end,
    EMVCActiveRecord);
end;

procedure TTestSoftDelete.TestRestoreOnAliveRaises;
var
  lC: TCustomerSDTimestamp;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'NeverDeleted';
    lC.Insert;
    Assert.WillRaise(
      procedure
      begin
        lC.Restore;
      end,
      EMVCActiveRecord,
      'Restore on a live record must raise EMVCActiveRecord');
  finally
    lC.Free;
  end;
end;

procedure TTestSoftDelete.TestHardDeleteBypassesSoftDelete;
var
  lC: TCustomerSDTimestamp;
  lID: Int64;
  lQry: TFDQuery;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'HardDel';
    lC.Insert;
    lID := lC.ID;
    lC.HardDelete;
  finally
    lC.Free;
  end;
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT COUNT(*) AS n FROM customers_sd WHERE id = :id';
    lQry.ParamByName('id').AsLargeInt := lID;
    lQry.Open;
    Assert.AreEqual(0, lQry.FieldByName('n').AsInteger,
      'HardDelete must remove the row physically');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestHardDeleteRQLBulk;
var
  lC: TCustomerSDTimestamp;
  lIDSoft: Int64;
  lIDHard: Int64;
  lQry: TFDQuery;
begin
  // Insert two rows; soft-delete one of them first
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'BulkHardA';
    lC.Insert;
    lIDSoft := lC.ID;
    lC.Delete; // soft-delete
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'BulkHardB';
    lC.Insert;
    lIDHard := lC.ID;
  finally
    lC.Free;
  end;
  // Hard-delete both via bulk RQL (match both names)
  TMVCActiveRecord.HardDeleteRQL<TCustomerSDTimestamp>(
    'in(Name,["BulkHardA","BulkHardB"])');
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text :=
      'SELECT COUNT(*) AS n FROM customers_sd WHERE id IN (:id1, :id2)';
    lQry.ParamByName('id1').AsLargeInt := lIDSoft;
    lQry.ParamByName('id2').AsLargeInt := lIDHard;
    lQry.Open;
    Assert.AreEqual(0, lQry.FieldByName('n').AsInteger,
      'HardDeleteRQL must physically remove all matching rows');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestRestoreRQLBulk;
var
  lC: TCustomerSDTimestamp;
  lID1: Int64;
  lID2: Int64;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'BulkRestoreA';
    lC.Insert;
    lID1 := lC.ID;
    lC.Delete;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'BulkRestoreB';
    lC.Insert;
    lID2 := lC.ID;
    lC.Delete;
  finally
    lC.Free;
  end;
  // Both are soft-deleted; restore them via bulk RQL
  TMVCActiveRecord.RestoreRQL<TCustomerSDTimestamp>(
    'in(Name,["BulkRestoreA","BulkRestoreB"])');
  // Now they should be visible in normal scope
  lList := TMVCActiveRecord.Where<TCustomerSDTimestamp>(
    'id IN (:id1, :id2)', [lID1, lID2]);
  try
    Assert.AreEqual<NativeInt>(2, lList.Count,
      'RestoreRQL must make both rows visible in normal scope');
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestDeleteRQLDispatchesSoftDelete;
var
  lC: TCustomerSDTimestamp;
  lID: Int64;
  lQry: TFDQuery;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'RQLDispatch';
    lC.Insert;
    lID := lC.ID;
  finally
    lC.Free;
  end;
  // DeleteRQL on a soft-delete class must do a soft-delete (UPDATE), not a physical DELETE
  TMVCActiveRecord.DeleteRQL<TCustomerSDTimestamp>('eq(Name,"RQLDispatch")');
  // Row must still exist physically
  lQry := TFDQuery.Create(nil);
  try
    lQry.Connection := FConn;
    lQry.SQL.Text := 'SELECT COUNT(*) AS n FROM customers_sd WHERE id = :id';
    lQry.ParamByName('id').AsLargeInt := lID;
    lQry.Open;
    Assert.AreEqual(1, lQry.FieldByName('n').AsInteger,
      'DeleteRQL on a soft-delete class must keep the row (UPDATE not DELETE)');
    // And the sentinel must be set
    lQry.Close;
    lQry.SQL.Text :=
      'SELECT deleted_at FROM customers_sd WHERE id = :id';
    lQry.ParamByName('id').AsLargeInt := lID;
    lQry.Open;
    Assert.IsFalse(lQry.FieldByName('deleted_at').IsNull,
      'deleted_at must be populated after DeleteRQL soft-delete dispatch');
  finally
    lQry.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectRQLAutoFiltersDeleted;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Alive';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Dead';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lList := TMVCActiveRecord.SelectRQL<TCustomerSDTimestamp>('eq(name,"Alive")', 100);
  try
    Assert.AreEqual<NativeInt>(1, lList.Count);
    Assert.AreEqual('Alive', lList[0].Name);
  finally
    lList.Free;
  end;
  lList := TMVCActiveRecord.SelectRQL<TCustomerSDTimestamp>('eq(name,"Dead")', 100);
  try
    Assert.AreEqual<NativeInt>(0, lList.Count, 'Dead must be filtered out');
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectRQLWithLimitAutoFiltersDeleted;
var
  lC: TCustomerSDTimestamp;
  lI: Integer;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  for lI := 1 to 5 do
  begin
    lC := TCustomerSDTimestamp.Create;
    try
      lC.Name := 'Alive' + IntToStr(lI);
      lC.Insert;
    finally
      lC.Free;
    end;
  end;
  for lI := 1 to 5 do
  begin
    lC := TCustomerSDTimestamp.Create;
    try
      lC.Name := 'Dead' + IntToStr(lI);
      lC.Insert;
      lC.Delete;
    finally
      lC.Free;
    end;
  end;
  lList := TMVCActiveRecord.SelectRQL<TCustomerSDTimestamp>(
    'eq(name,"Alive1");limit(0,10)', 100);
  try
    Assert.AreEqual<NativeInt>(1, lList.Count);
    Assert.AreEqual('Alive1', lList[0].Name);
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectRQLEmptyAutoFilter;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'A';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'B';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  lList := TMVCActiveRecord.SelectRQL<TCustomerSDTimestamp>('', 100);
  try
    Assert.AreEqual<NativeInt>(1, lList.Count);
    Assert.AreEqual('A', lList[0].Name);
  finally
    lList.Free;
  end;
end;

procedure TTestSoftDelete.TestSelectRQLBypassedByIncludeSoftDeleted;
var
  lC: TCustomerSDTimestamp;
  lList: TObjectList<TCustomerSDTimestamp>;
begin
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'X';
    lC.Insert;
  finally
    lC.Free;
  end;
  lC := TCustomerSDTimestamp.Create;
  try
    lC.Name := 'Y';
    lC.Insert;
    lC.Delete;
  finally
    lC.Free;
  end;
  TMVCActiveRecord.IncludeSoftDeleted(True);
  try
    lList := TMVCActiveRecord.SelectRQL<TCustomerSDTimestamp>('', 100);
    try
      Assert.AreEqual<NativeInt>(2, lList.Count,
        'IncludeSoftDeleted scope must bypass auto-filter');
    finally
      lList.Free;
    end;
  finally
    TMVCActiveRecord.IncludeSoftDeleted(False);
  end;
end;

{ TTestIsNew }

procedure TTestIsNew.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  FConn.ExecSQL(
    'CREATE TABLE isnew_nullable (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)');
  FConn.ExecSQL(
    'CREATE TABLE isnew_plain (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestIsNew.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestIsNew.TestFreshInstanceWithNullablePKIsNew;
var
  lE: TIsNewNullablePK;
begin
  lE := TIsNewNullablePK.Create;
  try
    Assert.IsTrue(lE.IsNew, 'A just-constructed entity must be IsNew');
    Assert.IsFalse(lE.IsPersisted);
  finally
    lE.Free;
  end;
end;

procedure TTestIsNew.TestFreshInstanceWithPlainPKIsNew;
var
  lE: TIsNewPlainPK;
begin
  lE := TIsNewPlainPK.Create;
  try
    // Plain Int64 default-constructs to 0 -> TValue.IsEmpty is True -> IsNew.
    Assert.IsTrue(lE.IsNew, 'Plain PK = 0 must be reported as new');
    Assert.IsFalse(lE.IsPersisted);
  finally
    lE.Free;
  end;
end;

procedure TTestIsNew.TestAfterInsertNotNew;
var
  lE: TIsNewNullablePK;
begin
  lE := TIsNewNullablePK.Create;
  try
    lE.Name := 'Alice';
    Assert.IsTrue(lE.IsNew, 'Sanity check: new before Insert');
    lE.Insert;
    Assert.IsFalse(lE.IsNew,
      'After Insert the auto-generated PK must be assigned -> not new anymore');
    Assert.IsTrue(lE.IsPersisted);
  finally
    lE.Free;
  end;
end;

procedure TTestIsNew.TestAfterLoadNotNew;
var
  lInsertedID: Int64;
  lInserted: TIsNewNullablePK;
  lLoaded: TIsNewNullablePK;
begin
  lInserted := TIsNewNullablePK.Create;
  try
    lInserted.Name := 'Bob';
    lInserted.Insert;
    lInsertedID := lInserted.ID.Value;
  finally
    lInserted.Free;
  end;

  lLoaded := TMVCActiveRecord.GetByPK<TIsNewNullablePK>(lInsertedID);
  try
    Assert.IsFalse(lLoaded.IsNew,
      'A row freshly loaded from the database must report IsPersisted');
    Assert.IsTrue(lLoaded.IsPersisted);
  finally
    lLoaded.Free;
  end;
end;

procedure TTestIsNew.TestIsPersistedIsNegationOfIsNew;
var
  lE: TIsNewNullablePK;
begin
  // Hard-lock the invariant so future refactors cannot let the two methods
  // drift apart silently.
  lE := TIsNewNullablePK.Create;
  try
    Assert.AreEqual(not lE.IsNew, lE.IsPersisted);
    lE.Name := 'Carol';
    lE.Insert;
    Assert.AreEqual(not lE.IsNew, lE.IsPersisted);
  finally
    lE.Free;
  end;
end;

{ TTestForefresh }

procedure TTestForefresh.SetUp;
begin
  FConn := TFDConnection.Create(nil);
  FConn.DriverName := 'SQLite';
  FConn.Params.Values['Database'] := ':memory:';
  FConn.Connected := True;
  // refreshable: 'name' is user-controlled. 'upper_name' is a computed
  // column (UPPER(name)) — the canonical case foRefresh covers, where
  // RETURNING / OUTPUT must surface the DB-computed value back into the
  // in-memory instance without an extra round-trip.
  // The 'notes' column is foRefresh too but is plain - used to verify
  // that foRefresh on a regular writable column simply round-trips.
  //
  // Computed columns on SQLite require 3.31+ (Jan 2020). The bundled
  // FireDAC SQLite engine on supported Delphi versions includes it.
  FConn.ExecSQL(
    'CREATE TABLE refreshable (' +
    '  id INTEGER PRIMARY KEY AUTOINCREMENT, ' +
    '  name TEXT, ' +
    '  upper_name TEXT GENERATED ALWAYS AS (UPPER(name)) STORED, ' +
    '  notes TEXT)');
  ActiveRecordConnectionsRegistry.AddDefaultConnection(FConn);
end;

procedure TTestForefresh.TearDown;
begin
  ActiveRecordConnectionsRegistry.RemoveDefaultConnection;
  FConn.Free;
end;

procedure TTestForefresh.TestInsertRefetchesTriggerOutput;
var
  lR: TRefreshable;
begin
  lR := TRefreshable.Create;
  try
    lR.Name := 'alice';
    Assert.IsFalse(lR.UpperName.HasValue,
      'UpperName must be NULL before Insert');
    lR.Insert;
    Assert.IsTrue(lR.UpperName.HasValue,
      'foRefresh must surface the trigger-written value');
    Assert.AreEqual('ALICE', lR.UpperName.Value,
      'Trigger must have uppercased the inserted name');
  finally
    lR.Free;
  end;
end;

procedure TTestForefresh.TestUpdateRefetchesTriggerOutput;
var
  lID: Int64;
  lR: TRefreshable;
begin
  lR := TRefreshable.Create;
  try
    lR.Name := 'alice';
    lR.Insert;
    lID := lR.ID;
  finally
    lR.Free;
  end;

  lR := TMVCActiveRecord.GetByPK<TRefreshable>(lID);
  try
    Assert.AreEqual('ALICE', lR.UpperName.Value,
      'Sanity check: state captured by the AFTER INSERT trigger');
    lR.Name := 'bob';
    lR.Update;
    Assert.AreEqual('BOB', lR.UpperName.Value,
      'foRefresh must refetch the trigger-rewritten value after Update');
  finally
    lR.Free;
  end;
end;

procedure TTestForefresh.TestForefreshFieldStaysWritable;
var
  lR: TRefreshable;
  lLoaded: TRefreshable;
  lID: Int64;
begin
  // foRefresh does NOT make a column read-only. If the caller writes it,
  // the value is persisted; the post-write SELECT just re-reads what's
  // there. For a column that no trigger touches, that means a clean
  // round-trip.
  lR := TRefreshable.Create;
  try
    lR.Name := 'bob';
    lR.Notes := 'user-written notes';
    lR.Insert;
    lID := lR.ID;
    Assert.IsTrue(lR.Notes.HasValue);
    Assert.AreEqual('user-written notes', lR.Notes.Value,
      'foRefresh must not blow away values the caller assigned');
  finally
    lR.Free;
  end;

  // Confirm by reloading from a fresh instance.
  lLoaded := TMVCActiveRecord.GetByPK<TRefreshable>(lID);
  try
    Assert.AreEqual('user-written notes', lLoaded.Notes.Value);
  finally
    lLoaded.Free;
  end;
end;

procedure TTestForefresh.TestPKAndForefreshBothFilled;
var
  lR: TRefreshable;
begin
  // Sanity: a single Insert must populate both the auto-generated PK and
  // every foRefresh field — the framework's RETURNING fetches the PK,
  // RefreshFromDB fetches the foRefresh columns.
  lR := TRefreshable.Create;
  try
    lR.Name := 'combined';
    lR.Notes := 'plain notes';
    lR.Insert;
    Assert.IsTrue(lR.ID > 0,             'PK must be filled');
    Assert.IsTrue(lR.UpperName.HasValue, 'UpperName must be filled by trigger');
    Assert.AreEqual('COMBINED', lR.UpperName.Value);
    Assert.AreEqual('plain notes', lR.Notes.Value);
  finally
    lR.Free;
  end;
end;

initialization
  TDUnitX.RegisterTestFixture(TTestSoftDelete);
  TDUnitX.RegisterTestFixture(TTestChangeTracking);
  TDUnitX.RegisterTestFixture(TTestForefresh);
  TDUnitX.RegisterTestFixture(TTestIsNew);

end.
