// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// *************************************************************************** }

unit SwaggerMiddlewareTestsU;

// Documents generated by TMVCSwaggerMiddleware (and the Swagger() HTTPFilter)
// fetched from an in-process server: Swagger 2.0 by default, OpenAPI 3 when
// the spec version is selected. TNativeOpenAPITests covers the native
// emitter (OpenAPI() filter) on Minimal API routes and controllers.
//
// Set the DMVC_SWAGGER_DUMP_DIR environment variable to also save the
// documents (swagger2.json, openapi3.json) there, e.g. to run them through an
// external OpenAPI validator.

interface

uses
  DUnitX.TestFramework,
  System.SysUtils,
  System.Generics.Collections,
  System.Net.HttpClient,
  JsonDataObjects,
  MVCFramework,
  MVCFramework.Commons,
  MVCFramework.Swagger.Commons,
  MVCFramework.Serializer.Commons,
  MVCFramework.Nullables,
  MVCFramework.Server.Intf;

const
  SWAGGER_TEST_PORT = 8896;
  NATIVE_TEST_PORT = 8897;
  CASE_TEST_PORT = 8898;
  SWAGGER_TEST_USER = 'swaguser';

type
  TSwagTestPerson = class
  private
    fID: Integer;
    fName: string;
    fNickName: string;
  public
    [MVCSwagJSONSchemaField(stInteger, 'id', 'Person identifier', False)]
    property ID: Integer read fID write fID;
    [MVCSwagJSONSchemaField(stString, 'name', 'Person name', True, False, 1, 100)]
    property Name: string read fName write fName;
    [MVCSwagJSONSchemaField(stString, 'nickname', 'Optional nickname', False, True)]
    property NickName: string read fNickName write fNickName;
  end;

  [MVCPath('/api/people')]
  [MVCSWAGDefaultModel(TSwagTestPerson, 'Person', 'People')]
  [MVCSWAGDefaultSummaryTags('People')]
  TSwagTestPeopleController = class(TMVCController)
  public
    [MVCPath]
    [MVCHTTPMethod([httpGET])]
    [MVCSwagSummary(TSwaggerConst.USE_DEFAULT_SUMMARY_TAGS, 'List people', 'getPeople')]
    [MVCSwagResponses(200, 'Success', SWAGUseDefaultControllerModel, True)]
    procedure GetPeople;

    [MVCPath('/($ID)')]
    [MVCHTTPMethod([httpGET])]
    [MVCSwagSummary(TSwaggerConst.USE_DEFAULT_SUMMARY_TAGS, 'Get a person', 'getPerson')]
    [MVCSwagResponses(200, 'Success', SWAGUseDefaultControllerModel)]
    [MVCSwagResponses(404, 'Not found')]
    procedure GetPerson(ID: Integer);

    [MVCPath]
    [MVCHTTPMethod([httpPOST])]
    [MVCSwagSummary(TSwaggerConst.USE_DEFAULT_SUMMARY_TAGS, 'Create a person', 'createPerson')]
    [MVCSwagParam(plBody, 'person', 'The person to create', SWAGUseDefaultControllerModel)]
    [MVCSwagResponses(201, 'Created')]
    [MVCRequiresAuthentication]
    procedure CreatePerson;

    [MVCPath('/($ID)')]
    [MVCHTTPMethod([httpDELETE])]
    [MVCSwagSummary(TSwaggerConst.USE_DEFAULT_SUMMARY_TAGS, 'Delete a person', 'deletePerson')]
    [MVCSwagResponses(204, 'Deleted')]
    [MVCSwagAuthentication(atBasic)]
    procedure DeletePerson(ID: Integer);
  end;

  // a path with a converter: the document must show {ID}, a string
  [MVCPath('/api/codes')]
  TSwagTestSqidsController = class(TMVCController)
  public
    [MVCPath('/($ID:sqids)')]
    [MVCHTTPMethod([httpGET])]
    [MVCSwagSummary('Codes', 'Get by sqid', 'getByCode')]
    procedure GetByCode(ID: Integer);
    // the action parameter is spelled differently from the placeholder
    [MVCPath('/byid/($ID)')]
    [MVCHTTPMethod([httpGET])]
    [MVCSwagSummary('Codes', 'Get by id', 'getByID')]
    procedure GetByID(id: Integer);
  end;

  // no action parameter: the path parameter comes from MVCSwagParam only,
  // spelled "id" while the placeholder is "($ID:sqids)"
  [MVCPath('/api/raw')]
  TSwagTestCaseController = class(TMVCController)
  public
    [MVCPath('/($ID:sqids)')]
    [MVCHTTPMethod([httpGET])]
    [MVCSwagSummary('Raw', 'Get by sqid', 'getRaw')]
    [MVCSwagParam(plPath, 'id', 'The sqid', ptInteger)]
    procedure GetRaw;
  end;

  TNativeItem = class
  private
    fFirstName: string;
    fCode: NullableInt32;
    fNickName: string;
  public
    property FirstName: string read fFirstName write fFirstName;
    property Code: NullableInt32 read fCode write fCode;
    [MVCNameAs('nick')]
    property NickName: string read fNickName write fNickName;
  end;

  TSwagTestAuthHandler = class(TInterfacedObject, IMVCAuthenticationHandler)
  protected
    procedure OnRequest(const AContext: TWebContext; const AControllerQualifiedClassName: string;
      const AActionName: string; var AAuthenticationRequired: Boolean);
    procedure OnAuthentication(const AContext: TWebContext; const AUserName: string;
      const APassword: string; AUserRoles: TList<string>; var AIsValid: Boolean;
      const ASessionData: TSessionData);
    procedure OnAuthorization(const AContext: TWebContext; AUserRoles: TList<string>;
      const AControllerQualifiedClassName: string; const AActionName: string;
      var AIsAuthorized: Boolean);
  end;

  [TestFixture]
  TSwaggerMiddlewareTests = class
  private
    FServer: IMVCServer;
    FCaseServer: IMVCServer;
    FClient: THTTPClient;
    function GetDoc(const APath: string; const APort: Integer = SWAGGER_TEST_PORT): string;
    function GetJSON(const APath: string; const APort: Integer = SWAGGER_TEST_PORT): TJsonObject;
  public
    [SetupFixture]
    procedure SetupFixture;
    [TeardownFixture]
    procedure TeardownFixture;

    [Test]
    procedure DefaultDocumentIsSwagger2;
    [Test]
    procedure ExplicitSwagger2IsIdenticalToDefault;
    [Test]
    procedure OpenAPI3DocumentHasComponentsNotDefinitions;
    [Test]
    procedure OpenAPI3SecuritySchemesAndRequirements;
    [Test]
    procedure OpenAPI3BodyParameterBecomesRequestBody;
    [Test]
    procedure OpenAPI3ServerIsRelativeToTheDocument;
    [Test]
    procedure OpenAPI3ServersUseAnExplicitHost;
    [Test]
    procedure DocumentHostKeepsThePortTheHostCarries;
    [Test]
    procedure SwagParamPathMatchesTheConverterIgnoringCase;
    [Test]
    procedure SwaggerFilterServesOpenAPI3;
    [Test]
    procedure PathConvertersBecomeTemplates;
    [Test]
    procedure SqidsPathParameterInBothVersions;
    [Test]
    procedure ActiveRecordRQLIsAStringQueryParameter;
    [Test]
    procedure Swagger2KeepsTheJWTApiKeyScheme;
    [Test]
    procedure RawTokenAsSwaggerUISendsItIsAccepted;
  end;

  [TestFixture]
  TNativeOpenAPITests = class
  private
    FServer: IMVCServer;
    FDoc: TJsonObject;
    FText: string;
  public
    [SetupFixture]
    procedure SetupFixture;
    [TeardownFixture]
    procedure TeardownFixture;
    [Test]
    procedure PathConstraintsBecomeTemplates;
    [Test]
    procedure ControllerPathParametersHaveTheRightType;
    [Test]
    procedure NullableIsATypeArray;
    [Test]
    procedure FieldNamesFollowTheSerializer;
    [Test]
    procedure ProducesDescribesTheDataEnvelope;
  end;

implementation

uses
  System.Classes,
  System.IOUtils,
  System.TypInfo, // lets ApplyNameCase (inline) expand: H2443 without it
  MVCFramework.JWT,
  MVCFramework.Middleware.JWT,
  MVCFramework.Middleware.Swagger,
  MVCFramework.Filters,
  MVCFramework.MinimalAPI,
  MVCFramework.ActiveRecordController,
  MVCFramework.OpenAPI3,
  MVCFramework.Server.Factory;

{ TSwagTestPeopleController }

procedure TSwagTestPeopleController.GetPeople;
begin
end;

procedure TSwagTestPeopleController.GetPerson(ID: Integer);
begin
end;

procedure TSwagTestPeopleController.CreatePerson;
begin
end;

procedure TSwagTestPeopleController.DeletePerson(ID: Integer);
begin
end;

procedure TSwagTestSqidsController.GetByCode(ID: Integer);
begin
end;

procedure TSwagTestSqidsController.GetByID(id: Integer);
begin
end;

procedure TSwagTestCaseController.GetRaw;
begin
end;

{ Saves a document in DMVC_SWAGGER_DUMP_DIR, when set, for the external validators }
procedure Dump(const AFileName, AContent: string);
var
  lDir: string;
begin
  lDir := GetEnvironmentVariable('DMVC_SWAGGER_DUMP_DIR');
  if lDir <> '' then
    TFile.WriteAllText(TPath.Combine(lDir, AFileName), AContent, TEncoding.UTF8);
end;

{ TSwagTestAuthHandler }

procedure TSwagTestAuthHandler.OnRequest(const AContext: TWebContext;
  const AControllerQualifiedClassName: string; const AActionName: string;
  var AAuthenticationRequired: Boolean);
begin
  AAuthenticationRequired := SameText(AActionName, 'CreatePerson');
end;

procedure TSwagTestAuthHandler.OnAuthentication(const AContext: TWebContext;
  const AUserName: string; const APassword: string; AUserRoles: TList<string>;
  var AIsValid: Boolean; const ASessionData: TSessionData);
begin
  AIsValid := (AUserName = SWAGGER_TEST_USER) and (APassword = SWAGGER_TEST_USER);
end;

procedure TSwagTestAuthHandler.OnAuthorization(const AContext: TWebContext;
  AUserRoles: TList<string>; const AControllerQualifiedClassName: string;
  const AActionName: string; var AIsAuthorized: Boolean);
begin
  AIsAuthorized := True;
end;

{ TSwaggerMiddlewareTests }

procedure TSwaggerMiddlewareTests.SetupFixture;
var
  lEngine: TMVCEngine;
  lInfo: TMVCSwaggerInfo;
begin
  lInfo.Title := 'Swagger middleware tests';
  lInfo.Version := 'v1';
  lInfo.Description := 'Documents generated by the unit tests';

  lEngine := TMVCEngine.Create;
  lEngine.AddController(TSwagTestPeopleController);
  lEngine.AddController(TSwagTestSqidsController);
  lEngine.AddController(TMVCActiveRecordController, '/api/entities');
  {old signature, untouched: the default must stay Swagger 2.0}
  lEngine.AddMiddleware(TMVCSwaggerMiddleware.Create(lEngine, lInfo, '/swagger.json'));
  lEngine.AddMiddleware(TMVCSwaggerMiddleware.Create(lEngine, lInfo, '/swagger2.json',
    JWT_DEFAULT_DESCRIPTION, False, '', '', '', [psHTTP, psHTTPS], False, ssvSwagger2));
  lEngine.AddMiddleware(TMVCSwaggerMiddleware.Create(lEngine, lInfo, '/openapi3.json',
    JWT_DEFAULT_DESCRIPTION, False, '', '', '', [psHTTP, psHTTPS], False, ssvOpenAPI3));
  lEngine.UseHTTPFilter(Swagger(lEngine, lInfo, '/filter/openapi3.json',
    JWT_DEFAULT_DESCRIPTION, False, '', '', '', [psHTTP, psHTTPS], False, ssvOpenAPI3));
  lEngine.AddMiddleware(TMVCSwaggerMiddleware.Create(lEngine, lInfo, '/openapi3-host.json',
    JWT_DEFAULT_DESCRIPTION, False, 'api.example.com', '', '', [psHTTP, psHTTPS], False, ssvOpenAPI3));
  lEngine.AddMiddleware(TMVCJWTAuthenticationMiddleware.Create(
    TSwagTestAuthHandler.Create,
    procedure(const JWT: TJWT)
    begin
      JWT.Claims.Issuer := 'swagger-tests';
      JWT.Claims.ExpirationTime := Now + 1;
    end,
    'swagger_tests_secret_not_used_to_sign_anything_7c1f',
    '/login',
    [TJWTCheckableClaim.ExpirationTime],
    300));
  FServer := TMVCServerFactory.CreateIndyDirect(lEngine);
  FServer.Listen(SWAGGER_TEST_PORT);

  {kept apart: its document is odd on purpose (parameter "id", placeholder "ID")}
  lEngine := TMVCEngine.Create;
  lEngine.AddController(TSwagTestCaseController);
  lEngine.AddMiddleware(TMVCSwaggerMiddleware.Create(lEngine, lInfo, '/openapi3.json',
    JWT_DEFAULT_DESCRIPTION, False, '', '', '', [psHTTP, psHTTPS], False, ssvOpenAPI3));
  FCaseServer := TMVCServerFactory.CreateIndyDirect(lEngine);
  FCaseServer.Listen(CASE_TEST_PORT);
  FClient := THTTPClient.Create;
end;

procedure TSwaggerMiddlewareTests.TeardownFixture;
begin
  FClient.Free;
  FServer.Stop;
  FServer := nil;
  FCaseServer.Stop;
  FCaseServer := nil;
end;

function TSwaggerMiddlewareTests.GetDoc(const APath: string; const APort: Integer): string;
var
  lResp: IHTTPResponse;
begin
  lResp := FClient.Get(Format('http://localhost:%d%s', [APort, APath]));
  Assert.AreEqual(200, lResp.StatusCode, APath);
  Result := lResp.ContentAsString(TEncoding.UTF8);
end;

function TSwaggerMiddlewareTests.GetJSON(const APath: string; const APort: Integer): TJsonObject;
begin
  Result := TJsonObject.Parse(GetDoc(APath, APort)) as TJsonObject;
end;

procedure TSwaggerMiddlewareTests.DefaultDocumentIsSwagger2;
var
  lText: string;
  lDoc: TJsonObject;
begin
  lText := GetDoc('/swagger.json');
  Dump('swagger2.json', lText);
  lDoc := TJsonObject.Parse(lText) as TJsonObject;
  try
    Assert.AreEqual('2.0', lDoc.S['swagger']);
    {Indy Direct hands over the whole Host header: the port must not be appended twice}
    Assert.AreEqual(Format('localhost:%d', [SWAGGER_TEST_PORT]), lDoc.S['host']);
    Assert.IsTrue(lDoc.Contains('definitions'), 'definitions');
    Assert.IsTrue(lDoc.Contains('securityDefinitions'), 'securityDefinitions');
    Assert.IsFalse(lDoc.Contains('openapi'), 'openapi');
    Assert.IsFalse(lDoc.Contains('components'), 'components');
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.ExplicitSwagger2IsIdenticalToDefault;
begin
  Assert.AreEqual(GetDoc('/swagger.json'), GetDoc('/swagger2.json'));
end;

procedure TSwaggerMiddlewareTests.OpenAPI3DocumentHasComponentsNotDefinitions;
var
  lText: string;
  lDoc: TJsonObject;
begin
  lText := GetDoc('/openapi3.json');
  Dump('openapi3.json', lText);
  lDoc := TJsonObject.Parse(lText) as TJsonObject;
  try
    Assert.StartsWith('3.', lDoc.S['openapi']);
    Assert.IsFalse(lDoc.Contains('swagger'), 'swagger');
    Assert.IsFalse(lDoc.Contains('definitions'), 'definitions');
    Assert.IsFalse(lDoc.Contains('securityDefinitions'), 'securityDefinitions');
    Assert.IsTrue(lDoc.O['components'].O['schemas'].Count > 0, 'components.schemas');
    Assert.AreEqual('Swagger middleware tests', lDoc.O['info'].S['title']);
    Assert.IsFalse(lText.Contains('#/definitions/'), 'a $ref still points to #/definitions/');
    Assert.IsTrue(lText.Contains('#/components/schemas/'), 'no $ref to #/components/schemas/');
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.OpenAPI3SecuritySchemesAndRequirements;
var
  lDoc: TJsonObject;
  lSchemes: TJsonObject;
begin
  lDoc := GetJSON('/openapi3.json');
  try
    lSchemes := lDoc.O['components'].O['securitySchemes'];
    {Swagger UI's Authorize box then takes the raw token and sends "Bearer <token>"}
    Assert.AreEqual('http', lSchemes.O['bearer'].S['type']);
    Assert.AreEqual('bearer', lSchemes.O['bearer'].S['scheme']);
    Assert.AreEqual('JWT', lSchemes.O['bearer'].S['bearerFormat']);
    Assert.IsFalse(lSchemes.O['bearer'].Contains('in'), 'in');
    Assert.AreEqual('http', lSchemes.O['basic'].S['type']);
    Assert.AreEqual('basic', lSchemes.O['basic'].S['scheme']);
    {MVCRequiresAuthentication -> bearer, MVCSwagAuthentication(atBasic) -> basic}
    Assert.IsTrue(lDoc.O['paths'].O['/api/people'].O['post'].A['security'].O[0].Contains('bearer'));
    Assert.IsTrue(lDoc.O['paths'].O['/api/people/{ID}'].O['delete'].A['security'].O[0].Contains('basic'));
    Assert.IsFalse(lDoc.O['paths'].O['/api/people'].O['get'].Contains('security'));
    {the JWT login endpoint of the JWT middleware is documented}
    Assert.IsTrue(lDoc.O['paths'].Contains('/login'), '/login');
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.OpenAPI3BodyParameterBecomesRequestBody;
var
  lDoc: TJsonObject;
  lPost: TJsonObject;
  lParam: TJsonObject;
  I: Integer;
begin
  lDoc := GetJSON('/openapi3.json');
  try
    lPost := lDoc.O['paths'].O['/api/people'].O['post'];
    Assert.IsTrue(lPost.O['requestBody'].O['content'].Contains('application/json'), 'requestBody');
    for I := 0 to lPost.A['parameters'].Count - 1 do
    begin
      lParam := lPost.A['parameters'].O[I];
      Assert.AreNotEqual('body', lParam.S['in']);
    end;
    Assert.AreEqual('path', lDoc.O['paths'].O['/api/people/{ID}'].O['get'].A['parameters'].O[0].S['in']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.OpenAPI3ServerIsRelativeToTheDocument;
var
  lText: string;
  lDoc: TJsonObject;
begin
  {the request Host header is not echoed: a relative server resolves against the
   URL the document was fetched from, so "Try it out" stays on the same origin}
  lText := GetDoc('/openapi3.json');
  Assert.IsFalse(lText.Contains('localhost'), 'the request host is in the document');
  lDoc := TJsonObject.Parse(lText) as TJsonObject;
  try
    Assert.IsFalse(lDoc.Contains('host'), 'host');
    Assert.IsFalse(lDoc.Contains('basePath'), 'basePath');
    Assert.IsFalse(lDoc.Contains('schemes'), 'schemes');
    Assert.AreEqual(1, lDoc.A['servers'].Count);
    Assert.AreEqual('/', lDoc.A['servers'].O[0].S['url']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.OpenAPI3ServersUseAnExplicitHost;
var
  lDoc: TJsonObject;
begin
  lDoc := GetJSON('/openapi3-host.json');
  try
    Assert.AreEqual('http://api.example.com/', lDoc.A['servers'].O[0].S['url']);
    Assert.AreEqual('https://api.example.com/', lDoc.A['servers'].O[1].S['url']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.DocumentHostKeepsThePortTheHostCarries;
begin
  Assert.AreEqual('localhost:8080', TMVCSwaggerMiddleware.DocumentHost('localhost', 8080));
  Assert.AreEqual('localhost:8080', TMVCSwaggerMiddleware.DocumentHost('localhost:8080', 8080));
  {behind a proxy the Host header port wins over the port the server listens on}
  Assert.AreEqual('localhost:9090', TMVCSwaggerMiddleware.DocumentHost('localhost:9090', 8080));
  Assert.AreEqual('[::1]:8080', TMVCSwaggerMiddleware.DocumentHost('[::1]', 8080));
  Assert.AreEqual('[::1]:8080', TMVCSwaggerMiddleware.DocumentHost('[::1]:8080', 8080));
  {no Host header: what master wrote}
  Assert.AreEqual(':8080', TMVCSwaggerMiddleware.DocumentHost('', 8080));
end;

procedure TSwaggerMiddlewareTests.SwagParamPathMatchesTheConverterIgnoringCase;
var
  lDoc: TJsonObject;
  lParam: TJsonObject;
begin
  lDoc := GetJSON('/openapi3.json', CASE_TEST_PORT);
  try
    lParam := lDoc.O['paths'].O['/api/raw/{ID}'].O['get'].A['parameters'].O[0];
    Assert.AreEqual('id', lParam.S['name']);
    Assert.AreEqual('path', lParam.S['in']);
    Assert.AreEqual('string', lParam.O['schema'].S['type']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.SwaggerFilterServesOpenAPI3;
begin
  Assert.AreEqual(GetDoc('/openapi3.json'), GetDoc('/filter/openapi3.json'));
end;

procedure TSwaggerMiddlewareTests.PathConvertersBecomeTemplates;
begin
  {the router accepts ($name) and ($name:converter), in a whole segment or inside one}
  Assert.AreEqual('/api/people/{ID}', TMVCSwagger.MVCPathToSwagPath('/api/people/($ID)'));
  Assert.AreEqual('/api/people/{ID}', TMVCSwagger.MVCPathToSwagPath('/api/people/($ID:sqids)'));
  Assert.AreEqual('/a/{x}/b/{y}.json', TMVCSwagger.MVCPathToSwagPath('/a/($x:sqids)/b/($y).json'));
end;

procedure TSwaggerMiddlewareTests.SqidsPathParameterInBothVersions;
var
  lDoc: TJsonObject;
  lText: string;
  lParam: TJsonObject;
begin
  lText := GetDoc('/swagger.json');
  Assert.IsFalse(lText.Contains('($'), 'Swagger 2 still has a DMVC path marker');
  lDoc := TJsonObject.Parse(lText) as TJsonObject;
  try
    lParam := lDoc.O['paths'].O['/api/codes/{ID}'].O['get'].A['parameters'].O[0];
    Assert.AreEqual('ID', lParam.S['name']);
    Assert.AreEqual('path', lParam.S['in']);
    {a sqid travels as a string, whatever the action parameter type is}
    Assert.AreEqual('string', lParam.S['type']);
  finally
    lDoc.Free;
  end;
  lText := GetDoc('/openapi3.json');
  Assert.IsFalse(lText.Contains('($'), 'OpenAPI 3 still has a DMVC path marker');
  lDoc := TJsonObject.Parse(lText) as TJsonObject;
  try
    lParam := lDoc.O['paths'].O['/api/codes/{ID}'].O['get'].A['parameters'].O[0];
    Assert.AreEqual('path', lParam.S['in']);
    Assert.AreEqual('string', lParam.O['schema'].S['type']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.ActiveRecordRQLIsAStringQueryParameter;
var
  lDoc: TJsonObject;
  lParam: TJsonObject;
begin
  lDoc := GetJSON('/openapi3.json');
  try
    lParam := lDoc.O['paths'].O['/api/entities/people/searches'].O['get'].A['parameters'].O[0];
    Assert.AreEqual('rql', lParam.S['name']);
    Assert.AreEqual('query', lParam.S['in']);
    Assert.AreEqual('string', lParam.O['schema'].S['type']);
    Assert.IsFalse(lParam.O['schema'].Contains('$ref'), '$ref');
  finally
    lDoc.Free;
  end;
  lDoc := GetJSON('/swagger.json');
  try
    lParam := lDoc.O['paths'].O['/api/entities/people/searches'].O['get'].A['parameters'].O[0];
    Assert.AreEqual('string', lParam.S['type']);
    Assert.IsFalse(lParam.Contains('schema'), 'schema');
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.Swagger2KeepsTheJWTApiKeyScheme;
var
  lDoc: TJsonObject;
begin
  {Swagger 2.0 has no http/bearer type}
  lDoc := GetJSON('/swagger.json');
  try
    Assert.AreEqual('apiKey', lDoc.O['securityDefinitions'].O['bearer'].S['type']);
    Assert.AreEqual('header', lDoc.O['securityDefinitions'].O['bearer'].S['in']);
    Assert.AreEqual('Authorization', lDoc.O['securityDefinitions'].O['bearer'].S['name']);
  finally
    lDoc.Free;
  end;
end;

procedure TSwaggerMiddlewareTests.RawTokenAsSwaggerUISendsItIsAccepted;
var
  lResp: IHTTPResponse;
  lToken: string;
  lJSON: TJsonObject;
  lURL: string;
begin
  lURL := Format('http://localhost:%d/api/people', [SWAGGER_TEST_PORT]);
  lResp := FClient.Post(lURL, TStream(nil));
  Assert.AreEqual(401, lResp.StatusCode, 'no token');

  FClient.CustomHeaders['jwtusername'] := SWAGGER_TEST_USER;
  FClient.CustomHeaders['jwtpassword'] := SWAGGER_TEST_USER;
  try
    lResp := FClient.Post(Format('http://localhost:%d/login', [SWAGGER_TEST_PORT]), TStream(nil));
  finally
    FClient.CustomHeaders['jwtusername'] := '';
    FClient.CustomHeaders['jwtpassword'] := '';
  end;
  Assert.AreEqual(200, lResp.StatusCode, 'login');
  lJSON := TJsonObject.Parse(lResp.ContentAsString(TEncoding.UTF8)) as TJsonObject;
  try
    lToken := lJSON.S['token'];
  finally
    lJSON.Free;
  end;
  Assert.IsNotEmpty(lToken);

  {what Swagger UI sends for an http/bearer scheme after Authorize with the raw token}
  FClient.CustomHeaders['Authorization'] := 'Bearer ' + lToken;
  try
    lResp := FClient.Post(lURL, TStream(nil));
  finally
    FClient.CustomHeaders['Authorization'] := '';
  end;
  Assert.IsTrue(lResp.StatusCode in [200, 201, 204], 'with token: ' + lResp.StatusCode.ToString);
end;

{ TNativeOpenAPITests }

procedure TNativeOpenAPITests.SetupFixture;
var
  lEngine: TMVCEngine;
  lInfo: TMVCOpenAPIInfo;
  lClient: THTTPClient;
begin
  lInfo.Title := 'Native emitter tests';
  lInfo.Version := 'v1';
  lEngine := TMVCEngine.Create;
  lEngine.AddController(TSwagTestSqidsController);
  lEngine.Root.MapGet<Integer>('/items/($id:int)',
    function(ID: Integer): IMVCResponse
    begin
      Result := Ok(TNativeItem.Create);
    end).Produces<TNativeItem>;
  lEngine.UseHTTPFilter(OpenAPI(lEngine, lInfo));
  FServer := TMVCServerFactory.CreateIndyDirect(lEngine);
  FServer.Listen(NATIVE_TEST_PORT);
  lClient := THTTPClient.Create;
  try
    FText := lClient.Get(Format('http://localhost:%d/openapi.json', [NATIVE_TEST_PORT])).ContentAsString(TEncoding.UTF8);
  finally
    lClient.Free;
  end;
  Dump('native.json', FText);
  FDoc := TJsonObject.Parse(FText) as TJsonObject;
end;

procedure TNativeOpenAPITests.TeardownFixture;
begin
  FDoc.Free;
  FServer.Stop;
  FServer := nil;
end;

procedure TNativeOpenAPITests.PathConstraintsBecomeTemplates;
begin
  Assert.IsFalse(FText.Contains('($'), 'a DMVC path marker is left');
  Assert.IsTrue(FDoc.O['paths'].Contains('/items/{id}'), '/items/{id}');
  Assert.IsTrue(FDoc.O['paths'].Contains('/api/codes/{ID}'), '/api/codes/{ID}');
  Assert.AreEqual('integer', FDoc.O['paths'].O['/items/{id}'].O['get'].A['parameters'].O[0].O['schema'].S['type']);
end;

procedure TNativeOpenAPITests.ControllerPathParametersHaveTheRightType;
var
  lParams: TJsonArray;
begin
  {($ID:sqids): the sqid travels as a string, whatever the action parameter type}
  lParams := FDoc.O['paths'].O['/api/codes/{ID}'].O['get'].A['parameters'];
  Assert.AreEqual(1, lParams.Count);
  Assert.AreEqual('path', lParams.O[0].S['in']);
  Assert.AreEqual('string', lParams.O[0].O['schema'].S['type']);
  {action parameter "id", placeholder "($ID)": one path parameter, not a query one plus a path one}
  lParams := FDoc.O['paths'].O['/api/codes/byid/{ID}'].O['get'].A['parameters'];
  Assert.AreEqual(1, lParams.Count, 'parameters');
  Assert.AreEqual('path', lParams.O[0].S['in']);
  Assert.AreEqual('ID', lParams.O[0].S['name']);
  Assert.AreEqual('integer', lParams.O[0].O['schema'].S['type']);
end;

procedure TNativeOpenAPITests.NullableIsATypeArray;
var
  lType: TJsonArray;
begin
  {OpenAPI 3.1 has no "nullable": a type array with "null" instead}
  Assert.IsFalse(FText.Contains('"nullable"'), 'nullable keyword');
  lType := FDoc.O['components'].O['schemas'].O['TNativeItem'].O['properties'].O['code'].A['type'];
  Assert.AreEqual(2, lType.Count);
  Assert.AreEqual('integer', lType.S[0]);
  Assert.AreEqual('null', lType.S[1]);
end;

procedure TNativeOpenAPITests.FieldNamesFollowTheSerializer;
var
  lProps: TJsonObject;
begin
  lProps := FDoc.O['components'].O['schemas'].O['TNativeItem'].O['properties'];
  {the names the serializer writes: MVCNameCaseDefault and MVCNameAs}
  Assert.IsTrue(lProps.Contains(TMVCSerializerHelper.ApplyNameCase(MVCNameCaseDefault, 'FirstName')), 'firstname');
  Assert.IsTrue(lProps.Contains('nick'), 'nick');
  Assert.IsFalse(lProps.Contains('NickName'), 'NickName');
end;

procedure TNativeOpenAPITests.ProducesDescribesTheDataEnvelope;
var
  lSchema: TJsonObject;
begin
  // Ok(Body) is rendered as {"data": Body}
  lSchema := FDoc.O['paths'].O['/items/{id}'].O['get'].O['responses'].O['200'].O['content']
    .O['application/json'].O['schema'];
  Assert.AreEqual('object', lSchema.S['type']);
  Assert.AreEqual('#/components/schemas/TNativeItem', lSchema.O['properties'].O['data'].S['$ref']);
end;

initialization

TDUnitX.RegisterTestFixture(TSwaggerMiddlewareTests);
TDUnitX.RegisterTestFixture(TNativeOpenAPITests);

end.
